/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2024 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
)

// checks if the UpdateListingDeprecatedRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateListingDeprecatedRequest{}

// UpdateListingDeprecatedRequest struct for UpdateListingDeprecatedRequest
type UpdateListingDeprecatedRequest struct {
	// An array of numeric image IDs of the images in a listing, which can include up to 10 images.
	ImageIds []int64 `json:"image_ids,omitempty"`
	// The listing's title string. When creating or updating a listing, valid title strings contain only letters, numbers, punctuation marks, mathematical symbols, whitespace characters, ™, ©, and ®. (regex: /[^\\p{L}\\p{Nd}\\p{P}\\p{Sm}\\p{Zs}™©®]/u) You can only use the %, :, & and + characters once each.
	Title *string `json:"title,omitempty"`
	// A description string of the product for sale in the listing.
	Description *string `json:"description,omitempty"`
	// A list of material strings for materials used in the product. Valid materials strings contain only letters, numbers, and whitespace characters. (regex: /[^\\p{L}\\p{Nd}\\p{Zs}]/u) Default value is null.
	Materials []string `json:"materials,omitempty"`
	// When true, renews a listing for four months upon expiration.
	ShouldAutoRenew *bool `json:"should_auto_renew,omitempty"`
	// The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is `physical`.
	ShippingProfileId NullableInt64 `json:"shipping_profile_id,omitempty"`
	// The numeric ID of the [shop section](/documentation/reference#tag/Shop-Section) for this listing. Default value is null.
	ShopSectionId NullableInt64 `json:"shop_section_id,omitempty"`
	// The numeric weight of the product measured in units set in 'item_weight_unit'. Default value is null. If set, the value must be greater than 0.
	ItemWeight NullableFloat32 `json:"item_weight,omitempty"`
	// The numeric length of the product measured in units set in 'item_dimensions_unit'. Default value is null. If set, the value must be greater than 0.
	ItemLength NullableFloat32 `json:"item_length,omitempty"`
	// The numeric width of the product measured in units set in 'item_dimensions_unit'. Default value is null. If set, the value must be greater than 0.
	ItemWidth NullableFloat32 `json:"item_width,omitempty"`
	// The numeric height of the product measured in units set in 'item_dimensions_unit'. Default value is null. If set, the value must be greater than 0.
	ItemHeight         NullableFloat32                                     `json:"item_height,omitempty"`
	ItemWeightUnit     NullableCreateDraftListingRequestItemWeightUnit     `json:"item_weight_unit,omitempty"`
	ItemDimensionsUnit NullableCreateDraftListingRequestItemDimensionsUnit `json:"item_dimensions_unit,omitempty"`
	// When true, applicable [shop](/documentation/reference#tag/Shop) tax rates apply to this listing at checkout.
	IsTaxable *bool `json:"is_taxable,omitempty"`
	// The numerical taxonomy ID of the listing. See [SellerTaxonomy](/documentation/reference#tag/SellerTaxonomy) and [BuyerTaxonomy](/documentation/reference#tag/BuyerTaxonomy) for more information.
	TaxonomyId *int64 `json:"taxonomy_id,omitempty"`
	// A comma-separated list of tag strings for the listing. When creating or updating a listing, valid tag strings contain only letters, numbers, whitespace characters, -, ', ™, ©, and ®. (regex: /[^\\p{L}\\p{Nd}\\p{Zs}\\-'™©®]/u) Default value is null.
	Tags     []string                           `json:"tags,omitempty"`
	WhoMade  *CreateDraftListingRequestWhoMade  `json:"who_made,omitempty"`
	WhenMade *CreateDraftListingRequestWhenMade `json:"when_made,omitempty"`
	// The positive non-zero numeric position in the featured listings of the shop, with rank 1 listings appearing in the left-most position in featured listing on a shop’s home page.
	FeaturedRank NullableInt64 `json:"featured_rank,omitempty"`
	// When true, this listing is personalizable. The default value is null.
	IsPersonalizable *bool `json:"is_personalizable,omitempty"`
	// When true, this listing requires personalization. The default value is null. Will only change if is_personalizable is 'true'.
	PersonalizationIsRequired *bool `json:"personalization_is_required,omitempty"`
	// This is an integer value representing the maximum length for the personalization message entered by the buyer. Will only change if is_personalizable is 'true'.
	PersonalizationCharCountMax *int64 `json:"personalization_char_count_max,omitempty"`
	// A string representing instructions for the buyer to enter the personalization. Will only change if is_personalizable is 'true'.
	PersonalizationInstructions *string                              `json:"personalization_instructions,omitempty"`
	State                       *UpdateListingDeprecatedRequestState `json:"state,omitempty"`
	// When true, tags the listing as a supply product, else indicates that it's a finished product. Helps buyers locate the listing under the Supplies heading. Requires 'who_made' and 'when_made'.
	IsSupply *bool `json:"is_supply,omitempty"`
	// An array of unique IDs of production partner ids.
	ProductionPartnerIds []int64                                    `json:"production_partner_ids,omitempty"`
	Type                 NullableUpdateListingDeprecatedRequestType `json:"type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateListingDeprecatedRequest UpdateListingDeprecatedRequest

// NewUpdateListingDeprecatedRequest instantiates a new UpdateListingDeprecatedRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateListingDeprecatedRequest() *UpdateListingDeprecatedRequest {
	this := UpdateListingDeprecatedRequest{}
	return &this
}

// NewUpdateListingDeprecatedRequestWithDefaults instantiates a new UpdateListingDeprecatedRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateListingDeprecatedRequestWithDefaults() *UpdateListingDeprecatedRequest {
	this := UpdateListingDeprecatedRequest{}
	return &this
}

// GetImageIds returns the ImageIds field value if set, zero value otherwise.
func (o *UpdateListingDeprecatedRequest) GetImageIds() []int64 {
	if o == nil || IsNil(o.ImageIds) {
		var ret []int64
		return ret
	}
	return o.ImageIds
}

// GetImageIdsOk returns a tuple with the ImageIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateListingDeprecatedRequest) GetImageIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.ImageIds) {
		return nil, false
	}
	return o.ImageIds, true
}

// HasImageIds returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasImageIds() bool {
	if o != nil && !IsNil(o.ImageIds) {
		return true
	}

	return false
}

// SetImageIds gets a reference to the given []int64 and assigns it to the ImageIds field.
func (o *UpdateListingDeprecatedRequest) SetImageIds(v []int64) {
	o.ImageIds = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *UpdateListingDeprecatedRequest) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateListingDeprecatedRequest) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *UpdateListingDeprecatedRequest) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateListingDeprecatedRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateListingDeprecatedRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateListingDeprecatedRequest) SetDescription(v string) {
	o.Description = &v
}

// GetMaterials returns the Materials field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateListingDeprecatedRequest) GetMaterials() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Materials
}

// GetMaterialsOk returns a tuple with the Materials field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateListingDeprecatedRequest) GetMaterialsOk() ([]string, bool) {
	if o == nil || IsNil(o.Materials) {
		return nil, false
	}
	return o.Materials, true
}

// HasMaterials returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasMaterials() bool {
	if o != nil && !IsNil(o.Materials) {
		return true
	}

	return false
}

// SetMaterials gets a reference to the given []string and assigns it to the Materials field.
func (o *UpdateListingDeprecatedRequest) SetMaterials(v []string) {
	o.Materials = v
}

// GetShouldAutoRenew returns the ShouldAutoRenew field value if set, zero value otherwise.
func (o *UpdateListingDeprecatedRequest) GetShouldAutoRenew() bool {
	if o == nil || IsNil(o.ShouldAutoRenew) {
		var ret bool
		return ret
	}
	return *o.ShouldAutoRenew
}

// GetShouldAutoRenewOk returns a tuple with the ShouldAutoRenew field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateListingDeprecatedRequest) GetShouldAutoRenewOk() (*bool, bool) {
	if o == nil || IsNil(o.ShouldAutoRenew) {
		return nil, false
	}
	return o.ShouldAutoRenew, true
}

// HasShouldAutoRenew returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasShouldAutoRenew() bool {
	if o != nil && !IsNil(o.ShouldAutoRenew) {
		return true
	}

	return false
}

// SetShouldAutoRenew gets a reference to the given bool and assigns it to the ShouldAutoRenew field.
func (o *UpdateListingDeprecatedRequest) SetShouldAutoRenew(v bool) {
	o.ShouldAutoRenew = &v
}

// GetShippingProfileId returns the ShippingProfileId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateListingDeprecatedRequest) GetShippingProfileId() int64 {
	if o == nil || IsNil(o.ShippingProfileId.Get()) {
		var ret int64
		return ret
	}
	return *o.ShippingProfileId.Get()
}

// GetShippingProfileIdOk returns a tuple with the ShippingProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateListingDeprecatedRequest) GetShippingProfileIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShippingProfileId.Get(), o.ShippingProfileId.IsSet()
}

// HasShippingProfileId returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasShippingProfileId() bool {
	if o != nil && o.ShippingProfileId.IsSet() {
		return true
	}

	return false
}

// SetShippingProfileId gets a reference to the given NullableInt64 and assigns it to the ShippingProfileId field.
func (o *UpdateListingDeprecatedRequest) SetShippingProfileId(v int64) {
	o.ShippingProfileId.Set(&v)
}

// SetShippingProfileIdNil sets the value for ShippingProfileId to be an explicit nil
func (o *UpdateListingDeprecatedRequest) SetShippingProfileIdNil() {
	o.ShippingProfileId.Set(nil)
}

// UnsetShippingProfileId ensures that no value is present for ShippingProfileId, not even an explicit nil
func (o *UpdateListingDeprecatedRequest) UnsetShippingProfileId() {
	o.ShippingProfileId.Unset()
}

// GetShopSectionId returns the ShopSectionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateListingDeprecatedRequest) GetShopSectionId() int64 {
	if o == nil || IsNil(o.ShopSectionId.Get()) {
		var ret int64
		return ret
	}
	return *o.ShopSectionId.Get()
}

// GetShopSectionIdOk returns a tuple with the ShopSectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateListingDeprecatedRequest) GetShopSectionIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShopSectionId.Get(), o.ShopSectionId.IsSet()
}

// HasShopSectionId returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasShopSectionId() bool {
	if o != nil && o.ShopSectionId.IsSet() {
		return true
	}

	return false
}

// SetShopSectionId gets a reference to the given NullableInt64 and assigns it to the ShopSectionId field.
func (o *UpdateListingDeprecatedRequest) SetShopSectionId(v int64) {
	o.ShopSectionId.Set(&v)
}

// SetShopSectionIdNil sets the value for ShopSectionId to be an explicit nil
func (o *UpdateListingDeprecatedRequest) SetShopSectionIdNil() {
	o.ShopSectionId.Set(nil)
}

// UnsetShopSectionId ensures that no value is present for ShopSectionId, not even an explicit nil
func (o *UpdateListingDeprecatedRequest) UnsetShopSectionId() {
	o.ShopSectionId.Unset()
}

// GetItemWeight returns the ItemWeight field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateListingDeprecatedRequest) GetItemWeight() float32 {
	if o == nil || IsNil(o.ItemWeight.Get()) {
		var ret float32
		return ret
	}
	return *o.ItemWeight.Get()
}

// GetItemWeightOk returns a tuple with the ItemWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateListingDeprecatedRequest) GetItemWeightOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemWeight.Get(), o.ItemWeight.IsSet()
}

// HasItemWeight returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasItemWeight() bool {
	if o != nil && o.ItemWeight.IsSet() {
		return true
	}

	return false
}

// SetItemWeight gets a reference to the given NullableFloat32 and assigns it to the ItemWeight field.
func (o *UpdateListingDeprecatedRequest) SetItemWeight(v float32) {
	o.ItemWeight.Set(&v)
}

// SetItemWeightNil sets the value for ItemWeight to be an explicit nil
func (o *UpdateListingDeprecatedRequest) SetItemWeightNil() {
	o.ItemWeight.Set(nil)
}

// UnsetItemWeight ensures that no value is present for ItemWeight, not even an explicit nil
func (o *UpdateListingDeprecatedRequest) UnsetItemWeight() {
	o.ItemWeight.Unset()
}

// GetItemLength returns the ItemLength field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateListingDeprecatedRequest) GetItemLength() float32 {
	if o == nil || IsNil(o.ItemLength.Get()) {
		var ret float32
		return ret
	}
	return *o.ItemLength.Get()
}

// GetItemLengthOk returns a tuple with the ItemLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateListingDeprecatedRequest) GetItemLengthOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemLength.Get(), o.ItemLength.IsSet()
}

// HasItemLength returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasItemLength() bool {
	if o != nil && o.ItemLength.IsSet() {
		return true
	}

	return false
}

// SetItemLength gets a reference to the given NullableFloat32 and assigns it to the ItemLength field.
func (o *UpdateListingDeprecatedRequest) SetItemLength(v float32) {
	o.ItemLength.Set(&v)
}

// SetItemLengthNil sets the value for ItemLength to be an explicit nil
func (o *UpdateListingDeprecatedRequest) SetItemLengthNil() {
	o.ItemLength.Set(nil)
}

// UnsetItemLength ensures that no value is present for ItemLength, not even an explicit nil
func (o *UpdateListingDeprecatedRequest) UnsetItemLength() {
	o.ItemLength.Unset()
}

// GetItemWidth returns the ItemWidth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateListingDeprecatedRequest) GetItemWidth() float32 {
	if o == nil || IsNil(o.ItemWidth.Get()) {
		var ret float32
		return ret
	}
	return *o.ItemWidth.Get()
}

// GetItemWidthOk returns a tuple with the ItemWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateListingDeprecatedRequest) GetItemWidthOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemWidth.Get(), o.ItemWidth.IsSet()
}

// HasItemWidth returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasItemWidth() bool {
	if o != nil && o.ItemWidth.IsSet() {
		return true
	}

	return false
}

// SetItemWidth gets a reference to the given NullableFloat32 and assigns it to the ItemWidth field.
func (o *UpdateListingDeprecatedRequest) SetItemWidth(v float32) {
	o.ItemWidth.Set(&v)
}

// SetItemWidthNil sets the value for ItemWidth to be an explicit nil
func (o *UpdateListingDeprecatedRequest) SetItemWidthNil() {
	o.ItemWidth.Set(nil)
}

// UnsetItemWidth ensures that no value is present for ItemWidth, not even an explicit nil
func (o *UpdateListingDeprecatedRequest) UnsetItemWidth() {
	o.ItemWidth.Unset()
}

// GetItemHeight returns the ItemHeight field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateListingDeprecatedRequest) GetItemHeight() float32 {
	if o == nil || IsNil(o.ItemHeight.Get()) {
		var ret float32
		return ret
	}
	return *o.ItemHeight.Get()
}

// GetItemHeightOk returns a tuple with the ItemHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateListingDeprecatedRequest) GetItemHeightOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemHeight.Get(), o.ItemHeight.IsSet()
}

// HasItemHeight returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasItemHeight() bool {
	if o != nil && o.ItemHeight.IsSet() {
		return true
	}

	return false
}

// SetItemHeight gets a reference to the given NullableFloat32 and assigns it to the ItemHeight field.
func (o *UpdateListingDeprecatedRequest) SetItemHeight(v float32) {
	o.ItemHeight.Set(&v)
}

// SetItemHeightNil sets the value for ItemHeight to be an explicit nil
func (o *UpdateListingDeprecatedRequest) SetItemHeightNil() {
	o.ItemHeight.Set(nil)
}

// UnsetItemHeight ensures that no value is present for ItemHeight, not even an explicit nil
func (o *UpdateListingDeprecatedRequest) UnsetItemHeight() {
	o.ItemHeight.Unset()
}

// GetItemWeightUnit returns the ItemWeightUnit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateListingDeprecatedRequest) GetItemWeightUnit() CreateDraftListingRequestItemWeightUnit {
	if o == nil || IsNil(o.ItemWeightUnit.Get()) {
		var ret CreateDraftListingRequestItemWeightUnit
		return ret
	}
	return *o.ItemWeightUnit.Get()
}

// GetItemWeightUnitOk returns a tuple with the ItemWeightUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateListingDeprecatedRequest) GetItemWeightUnitOk() (*CreateDraftListingRequestItemWeightUnit, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemWeightUnit.Get(), o.ItemWeightUnit.IsSet()
}

// HasItemWeightUnit returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasItemWeightUnit() bool {
	if o != nil && o.ItemWeightUnit.IsSet() {
		return true
	}

	return false
}

// SetItemWeightUnit gets a reference to the given NullableCreateDraftListingRequestItemWeightUnit and assigns it to the ItemWeightUnit field.
func (o *UpdateListingDeprecatedRequest) SetItemWeightUnit(v CreateDraftListingRequestItemWeightUnit) {
	o.ItemWeightUnit.Set(&v)
}

// SetItemWeightUnitNil sets the value for ItemWeightUnit to be an explicit nil
func (o *UpdateListingDeprecatedRequest) SetItemWeightUnitNil() {
	o.ItemWeightUnit.Set(nil)
}

// UnsetItemWeightUnit ensures that no value is present for ItemWeightUnit, not even an explicit nil
func (o *UpdateListingDeprecatedRequest) UnsetItemWeightUnit() {
	o.ItemWeightUnit.Unset()
}

// GetItemDimensionsUnit returns the ItemDimensionsUnit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateListingDeprecatedRequest) GetItemDimensionsUnit() CreateDraftListingRequestItemDimensionsUnit {
	if o == nil || IsNil(o.ItemDimensionsUnit.Get()) {
		var ret CreateDraftListingRequestItemDimensionsUnit
		return ret
	}
	return *o.ItemDimensionsUnit.Get()
}

// GetItemDimensionsUnitOk returns a tuple with the ItemDimensionsUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateListingDeprecatedRequest) GetItemDimensionsUnitOk() (*CreateDraftListingRequestItemDimensionsUnit, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemDimensionsUnit.Get(), o.ItemDimensionsUnit.IsSet()
}

// HasItemDimensionsUnit returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasItemDimensionsUnit() bool {
	if o != nil && o.ItemDimensionsUnit.IsSet() {
		return true
	}

	return false
}

// SetItemDimensionsUnit gets a reference to the given NullableCreateDraftListingRequestItemDimensionsUnit and assigns it to the ItemDimensionsUnit field.
func (o *UpdateListingDeprecatedRequest) SetItemDimensionsUnit(v CreateDraftListingRequestItemDimensionsUnit) {
	o.ItemDimensionsUnit.Set(&v)
}

// SetItemDimensionsUnitNil sets the value for ItemDimensionsUnit to be an explicit nil
func (o *UpdateListingDeprecatedRequest) SetItemDimensionsUnitNil() {
	o.ItemDimensionsUnit.Set(nil)
}

// UnsetItemDimensionsUnit ensures that no value is present for ItemDimensionsUnit, not even an explicit nil
func (o *UpdateListingDeprecatedRequest) UnsetItemDimensionsUnit() {
	o.ItemDimensionsUnit.Unset()
}

// GetIsTaxable returns the IsTaxable field value if set, zero value otherwise.
func (o *UpdateListingDeprecatedRequest) GetIsTaxable() bool {
	if o == nil || IsNil(o.IsTaxable) {
		var ret bool
		return ret
	}
	return *o.IsTaxable
}

// GetIsTaxableOk returns a tuple with the IsTaxable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateListingDeprecatedRequest) GetIsTaxableOk() (*bool, bool) {
	if o == nil || IsNil(o.IsTaxable) {
		return nil, false
	}
	return o.IsTaxable, true
}

// HasIsTaxable returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasIsTaxable() bool {
	if o != nil && !IsNil(o.IsTaxable) {
		return true
	}

	return false
}

// SetIsTaxable gets a reference to the given bool and assigns it to the IsTaxable field.
func (o *UpdateListingDeprecatedRequest) SetIsTaxable(v bool) {
	o.IsTaxable = &v
}

// GetTaxonomyId returns the TaxonomyId field value if set, zero value otherwise.
func (o *UpdateListingDeprecatedRequest) GetTaxonomyId() int64 {
	if o == nil || IsNil(o.TaxonomyId) {
		var ret int64
		return ret
	}
	return *o.TaxonomyId
}

// GetTaxonomyIdOk returns a tuple with the TaxonomyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateListingDeprecatedRequest) GetTaxonomyIdOk() (*int64, bool) {
	if o == nil || IsNil(o.TaxonomyId) {
		return nil, false
	}
	return o.TaxonomyId, true
}

// HasTaxonomyId returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasTaxonomyId() bool {
	if o != nil && !IsNil(o.TaxonomyId) {
		return true
	}

	return false
}

// SetTaxonomyId gets a reference to the given int64 and assigns it to the TaxonomyId field.
func (o *UpdateListingDeprecatedRequest) SetTaxonomyId(v int64) {
	o.TaxonomyId = &v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateListingDeprecatedRequest) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateListingDeprecatedRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *UpdateListingDeprecatedRequest) SetTags(v []string) {
	o.Tags = v
}

// GetWhoMade returns the WhoMade field value if set, zero value otherwise.
func (o *UpdateListingDeprecatedRequest) GetWhoMade() CreateDraftListingRequestWhoMade {
	if o == nil || IsNil(o.WhoMade) {
		var ret CreateDraftListingRequestWhoMade
		return ret
	}
	return *o.WhoMade
}

// GetWhoMadeOk returns a tuple with the WhoMade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateListingDeprecatedRequest) GetWhoMadeOk() (*CreateDraftListingRequestWhoMade, bool) {
	if o == nil || IsNil(o.WhoMade) {
		return nil, false
	}
	return o.WhoMade, true
}

// HasWhoMade returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasWhoMade() bool {
	if o != nil && !IsNil(o.WhoMade) {
		return true
	}

	return false
}

// SetWhoMade gets a reference to the given CreateDraftListingRequestWhoMade and assigns it to the WhoMade field.
func (o *UpdateListingDeprecatedRequest) SetWhoMade(v CreateDraftListingRequestWhoMade) {
	o.WhoMade = &v
}

// GetWhenMade returns the WhenMade field value if set, zero value otherwise.
func (o *UpdateListingDeprecatedRequest) GetWhenMade() CreateDraftListingRequestWhenMade {
	if o == nil || IsNil(o.WhenMade) {
		var ret CreateDraftListingRequestWhenMade
		return ret
	}
	return *o.WhenMade
}

// GetWhenMadeOk returns a tuple with the WhenMade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateListingDeprecatedRequest) GetWhenMadeOk() (*CreateDraftListingRequestWhenMade, bool) {
	if o == nil || IsNil(o.WhenMade) {
		return nil, false
	}
	return o.WhenMade, true
}

// HasWhenMade returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasWhenMade() bool {
	if o != nil && !IsNil(o.WhenMade) {
		return true
	}

	return false
}

// SetWhenMade gets a reference to the given CreateDraftListingRequestWhenMade and assigns it to the WhenMade field.
func (o *UpdateListingDeprecatedRequest) SetWhenMade(v CreateDraftListingRequestWhenMade) {
	o.WhenMade = &v
}

// GetFeaturedRank returns the FeaturedRank field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateListingDeprecatedRequest) GetFeaturedRank() int64 {
	if o == nil || IsNil(o.FeaturedRank.Get()) {
		var ret int64
		return ret
	}
	return *o.FeaturedRank.Get()
}

// GetFeaturedRankOk returns a tuple with the FeaturedRank field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateListingDeprecatedRequest) GetFeaturedRankOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.FeaturedRank.Get(), o.FeaturedRank.IsSet()
}

// HasFeaturedRank returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasFeaturedRank() bool {
	if o != nil && o.FeaturedRank.IsSet() {
		return true
	}

	return false
}

// SetFeaturedRank gets a reference to the given NullableInt64 and assigns it to the FeaturedRank field.
func (o *UpdateListingDeprecatedRequest) SetFeaturedRank(v int64) {
	o.FeaturedRank.Set(&v)
}

// SetFeaturedRankNil sets the value for FeaturedRank to be an explicit nil
func (o *UpdateListingDeprecatedRequest) SetFeaturedRankNil() {
	o.FeaturedRank.Set(nil)
}

// UnsetFeaturedRank ensures that no value is present for FeaturedRank, not even an explicit nil
func (o *UpdateListingDeprecatedRequest) UnsetFeaturedRank() {
	o.FeaturedRank.Unset()
}

// GetIsPersonalizable returns the IsPersonalizable field value if set, zero value otherwise.
func (o *UpdateListingDeprecatedRequest) GetIsPersonalizable() bool {
	if o == nil || IsNil(o.IsPersonalizable) {
		var ret bool
		return ret
	}
	return *o.IsPersonalizable
}

// GetIsPersonalizableOk returns a tuple with the IsPersonalizable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateListingDeprecatedRequest) GetIsPersonalizableOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPersonalizable) {
		return nil, false
	}
	return o.IsPersonalizable, true
}

// HasIsPersonalizable returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasIsPersonalizable() bool {
	if o != nil && !IsNil(o.IsPersonalizable) {
		return true
	}

	return false
}

// SetIsPersonalizable gets a reference to the given bool and assigns it to the IsPersonalizable field.
func (o *UpdateListingDeprecatedRequest) SetIsPersonalizable(v bool) {
	o.IsPersonalizable = &v
}

// GetPersonalizationIsRequired returns the PersonalizationIsRequired field value if set, zero value otherwise.
func (o *UpdateListingDeprecatedRequest) GetPersonalizationIsRequired() bool {
	if o == nil || IsNil(o.PersonalizationIsRequired) {
		var ret bool
		return ret
	}
	return *o.PersonalizationIsRequired
}

// GetPersonalizationIsRequiredOk returns a tuple with the PersonalizationIsRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateListingDeprecatedRequest) GetPersonalizationIsRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.PersonalizationIsRequired) {
		return nil, false
	}
	return o.PersonalizationIsRequired, true
}

// HasPersonalizationIsRequired returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasPersonalizationIsRequired() bool {
	if o != nil && !IsNil(o.PersonalizationIsRequired) {
		return true
	}

	return false
}

// SetPersonalizationIsRequired gets a reference to the given bool and assigns it to the PersonalizationIsRequired field.
func (o *UpdateListingDeprecatedRequest) SetPersonalizationIsRequired(v bool) {
	o.PersonalizationIsRequired = &v
}

// GetPersonalizationCharCountMax returns the PersonalizationCharCountMax field value if set, zero value otherwise.
func (o *UpdateListingDeprecatedRequest) GetPersonalizationCharCountMax() int64 {
	if o == nil || IsNil(o.PersonalizationCharCountMax) {
		var ret int64
		return ret
	}
	return *o.PersonalizationCharCountMax
}

// GetPersonalizationCharCountMaxOk returns a tuple with the PersonalizationCharCountMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateListingDeprecatedRequest) GetPersonalizationCharCountMaxOk() (*int64, bool) {
	if o == nil || IsNil(o.PersonalizationCharCountMax) {
		return nil, false
	}
	return o.PersonalizationCharCountMax, true
}

// HasPersonalizationCharCountMax returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasPersonalizationCharCountMax() bool {
	if o != nil && !IsNil(o.PersonalizationCharCountMax) {
		return true
	}

	return false
}

// SetPersonalizationCharCountMax gets a reference to the given int64 and assigns it to the PersonalizationCharCountMax field.
func (o *UpdateListingDeprecatedRequest) SetPersonalizationCharCountMax(v int64) {
	o.PersonalizationCharCountMax = &v
}

// GetPersonalizationInstructions returns the PersonalizationInstructions field value if set, zero value otherwise.
func (o *UpdateListingDeprecatedRequest) GetPersonalizationInstructions() string {
	if o == nil || IsNil(o.PersonalizationInstructions) {
		var ret string
		return ret
	}
	return *o.PersonalizationInstructions
}

// GetPersonalizationInstructionsOk returns a tuple with the PersonalizationInstructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateListingDeprecatedRequest) GetPersonalizationInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.PersonalizationInstructions) {
		return nil, false
	}
	return o.PersonalizationInstructions, true
}

// HasPersonalizationInstructions returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasPersonalizationInstructions() bool {
	if o != nil && !IsNil(o.PersonalizationInstructions) {
		return true
	}

	return false
}

// SetPersonalizationInstructions gets a reference to the given string and assigns it to the PersonalizationInstructions field.
func (o *UpdateListingDeprecatedRequest) SetPersonalizationInstructions(v string) {
	o.PersonalizationInstructions = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *UpdateListingDeprecatedRequest) GetState() UpdateListingDeprecatedRequestState {
	if o == nil || IsNil(o.State) {
		var ret UpdateListingDeprecatedRequestState
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateListingDeprecatedRequest) GetStateOk() (*UpdateListingDeprecatedRequestState, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given UpdateListingDeprecatedRequestState and assigns it to the State field.
func (o *UpdateListingDeprecatedRequest) SetState(v UpdateListingDeprecatedRequestState) {
	o.State = &v
}

// GetIsSupply returns the IsSupply field value if set, zero value otherwise.
func (o *UpdateListingDeprecatedRequest) GetIsSupply() bool {
	if o == nil || IsNil(o.IsSupply) {
		var ret bool
		return ret
	}
	return *o.IsSupply
}

// GetIsSupplyOk returns a tuple with the IsSupply field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateListingDeprecatedRequest) GetIsSupplyOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSupply) {
		return nil, false
	}
	return o.IsSupply, true
}

// HasIsSupply returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasIsSupply() bool {
	if o != nil && !IsNil(o.IsSupply) {
		return true
	}

	return false
}

// SetIsSupply gets a reference to the given bool and assigns it to the IsSupply field.
func (o *UpdateListingDeprecatedRequest) SetIsSupply(v bool) {
	o.IsSupply = &v
}

// GetProductionPartnerIds returns the ProductionPartnerIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateListingDeprecatedRequest) GetProductionPartnerIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}
	return o.ProductionPartnerIds
}

// GetProductionPartnerIdsOk returns a tuple with the ProductionPartnerIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateListingDeprecatedRequest) GetProductionPartnerIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.ProductionPartnerIds) {
		return nil, false
	}
	return o.ProductionPartnerIds, true
}

// HasProductionPartnerIds returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasProductionPartnerIds() bool {
	if o != nil && !IsNil(o.ProductionPartnerIds) {
		return true
	}

	return false
}

// SetProductionPartnerIds gets a reference to the given []int64 and assigns it to the ProductionPartnerIds field.
func (o *UpdateListingDeprecatedRequest) SetProductionPartnerIds(v []int64) {
	o.ProductionPartnerIds = v
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateListingDeprecatedRequest) GetType() UpdateListingDeprecatedRequestType {
	if o == nil || IsNil(o.Type.Get()) {
		var ret UpdateListingDeprecatedRequestType
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateListingDeprecatedRequest) GetTypeOk() (*UpdateListingDeprecatedRequestType, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *UpdateListingDeprecatedRequest) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableUpdateListingDeprecatedRequestType and assigns it to the Type field.
func (o *UpdateListingDeprecatedRequest) SetType(v UpdateListingDeprecatedRequestType) {
	o.Type.Set(&v)
}

// SetTypeNil sets the value for Type to be an explicit nil
func (o *UpdateListingDeprecatedRequest) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *UpdateListingDeprecatedRequest) UnsetType() {
	o.Type.Unset()
}

func (o UpdateListingDeprecatedRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateListingDeprecatedRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ImageIds) {
		toSerialize["image_ids"] = o.ImageIds
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.Materials != nil {
		toSerialize["materials"] = o.Materials
	}
	if !IsNil(o.ShouldAutoRenew) {
		toSerialize["should_auto_renew"] = o.ShouldAutoRenew
	}
	if o.ShippingProfileId.IsSet() {
		toSerialize["shipping_profile_id"] = o.ShippingProfileId.Get()
	}
	if o.ShopSectionId.IsSet() {
		toSerialize["shop_section_id"] = o.ShopSectionId.Get()
	}
	if o.ItemWeight.IsSet() {
		toSerialize["item_weight"] = o.ItemWeight.Get()
	}
	if o.ItemLength.IsSet() {
		toSerialize["item_length"] = o.ItemLength.Get()
	}
	if o.ItemWidth.IsSet() {
		toSerialize["item_width"] = o.ItemWidth.Get()
	}
	if o.ItemHeight.IsSet() {
		toSerialize["item_height"] = o.ItemHeight.Get()
	}
	if o.ItemWeightUnit.IsSet() {
		toSerialize["item_weight_unit"] = o.ItemWeightUnit.Get()
	}
	if o.ItemDimensionsUnit.IsSet() {
		toSerialize["item_dimensions_unit"] = o.ItemDimensionsUnit.Get()
	}
	if !IsNil(o.IsTaxable) {
		toSerialize["is_taxable"] = o.IsTaxable
	}
	if !IsNil(o.TaxonomyId) {
		toSerialize["taxonomy_id"] = o.TaxonomyId
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.WhoMade) {
		toSerialize["who_made"] = o.WhoMade
	}
	if !IsNil(o.WhenMade) {
		toSerialize["when_made"] = o.WhenMade
	}
	if o.FeaturedRank.IsSet() {
		toSerialize["featured_rank"] = o.FeaturedRank.Get()
	}
	if !IsNil(o.IsPersonalizable) {
		toSerialize["is_personalizable"] = o.IsPersonalizable
	}
	if !IsNil(o.PersonalizationIsRequired) {
		toSerialize["personalization_is_required"] = o.PersonalizationIsRequired
	}
	if !IsNil(o.PersonalizationCharCountMax) {
		toSerialize["personalization_char_count_max"] = o.PersonalizationCharCountMax
	}
	if !IsNil(o.PersonalizationInstructions) {
		toSerialize["personalization_instructions"] = o.PersonalizationInstructions
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.IsSupply) {
		toSerialize["is_supply"] = o.IsSupply
	}
	if o.ProductionPartnerIds != nil {
		toSerialize["production_partner_ids"] = o.ProductionPartnerIds
	}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateListingDeprecatedRequest struct {
	value *UpdateListingDeprecatedRequest
	isSet bool
}

func (v NullableUpdateListingDeprecatedRequest) Get() *UpdateListingDeprecatedRequest {
	return v.value
}

func (v *NullableUpdateListingDeprecatedRequest) Set(val *UpdateListingDeprecatedRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateListingDeprecatedRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateListingDeprecatedRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateListingDeprecatedRequest(val *UpdateListingDeprecatedRequest) *NullableUpdateListingDeprecatedRequest {
	return &NullableUpdateListingDeprecatedRequest{value: val, isSet: true}
}

func (v NullableUpdateListingDeprecatedRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateListingDeprecatedRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
