/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2026 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
	"fmt"
	"strings"
	"unicode"
)

// UpdateListingRequestItemDimensionsUnit A string defining the units used to measure the dimensions of the product. Default value is null.
type UpdateListingRequestItemDimensionsUnit string

// List of updateListing_request_item_dimensions_unit
const (
	UPDATELISTINGREQUESTITEMDIMENSIONSUNIT_EMPTY  UpdateListingRequestItemDimensionsUnit = ""
	UPDATELISTINGREQUESTITEMDIMENSIONSUNIT_IN     UpdateListingRequestItemDimensionsUnit = "in"
	UPDATELISTINGREQUESTITEMDIMENSIONSUNIT_FT     UpdateListingRequestItemDimensionsUnit = "ft"
	UPDATELISTINGREQUESTITEMDIMENSIONSUNIT_MM     UpdateListingRequestItemDimensionsUnit = "mm"
	UPDATELISTINGREQUESTITEMDIMENSIONSUNIT_CM     UpdateListingRequestItemDimensionsUnit = "cm"
	UPDATELISTINGREQUESTITEMDIMENSIONSUNIT_M      UpdateListingRequestItemDimensionsUnit = "m"
	UPDATELISTINGREQUESTITEMDIMENSIONSUNIT_YD     UpdateListingRequestItemDimensionsUnit = "yd"
	UPDATELISTINGREQUESTITEMDIMENSIONSUNIT_INCHES UpdateListingRequestItemDimensionsUnit = "inches"
)

// All allowed values of UpdateListingRequestItemDimensionsUnit enum
var AllowedUpdateListingRequestItemDimensionsUnitEnumValues = []UpdateListingRequestItemDimensionsUnit{
	"",
	"in",
	"ft",
	"mm",
	"cm",
	"m",
	"yd",
	"inches",
}

var AllowedUpdateListingRequestItemDimensionsUnitEnumValuesValidator = map[interface{}]struct{}{
	UpdateListingRequestItemDimensionsUnit("").Ptr().generateNormalizedEnum():       struct{}{},
	UpdateListingRequestItemDimensionsUnit("in").Ptr().generateNormalizedEnum():     struct{}{},
	UpdateListingRequestItemDimensionsUnit("ft").Ptr().generateNormalizedEnum():     struct{}{},
	UpdateListingRequestItemDimensionsUnit("mm").Ptr().generateNormalizedEnum():     struct{}{},
	UpdateListingRequestItemDimensionsUnit("cm").Ptr().generateNormalizedEnum():     struct{}{},
	UpdateListingRequestItemDimensionsUnit("m").Ptr().generateNormalizedEnum():      struct{}{},
	UpdateListingRequestItemDimensionsUnit("yd").Ptr().generateNormalizedEnum():     struct{}{},
	UpdateListingRequestItemDimensionsUnit("inches").Ptr().generateNormalizedEnum(): struct{}{},
}

func (v *UpdateListingRequestItemDimensionsUnit) generateNormalizedEnum() any {
	if v == nil {
		return nil
	}

	s := *v
	var sb strings.Builder
	sb.Grow(len(s) + 2)     // Preallocate memory for efficiency
	var prevUnderscore bool // Track consecutive underscores
	for i, r := range s {
		switch {
		case unicode.IsUpper(r):
			// Add an underscore if:
			// 1. Not the first character
			// 2. Previous character is NOT uppercase (to handle acronyms like "HTTPRequest")
			// 3. Next character is lowercase (to avoid splitting acronyms)
			if i > 0 && (!unicode.IsUpper(rune(s[i-1])) || (i+1 < len(s) && unicode.IsLower(rune(s[i+1])))) {
				sb.WriteByte('_')
			}
			sb.WriteRune(unicode.ToLower(r))
			prevUnderscore = false

		case unicode.IsSpace(r) || r == '-' || r == '_': // Convert spaces, dashes, and underscores to `_`
			if !prevUnderscore { // Avoid consecutive `_`
				sb.WriteByte('_')
				prevUnderscore = true
			}

		case unicode.IsLetter(r) || unicode.IsDigit(r): // Keep letters and numbers
			sb.WriteRune(r)
			prevUnderscore = false

		default:
			// Ignore symbols (e.g., `@#$%&*!`)
		}
	}

	// Trim leading/trailing underscores
	return strings.Trim(sb.String(), "_")

}

func (v *UpdateListingRequestItemDimensionsUnit) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UpdateListingRequestItemDimensionsUnit(value)
	if _, existing := AllowedUpdateListingRequestItemDimensionsUnitEnumValuesValidator[enumTypeValue.Ptr().generateNormalizedEnum()]; existing {
		*v = enumTypeValue
		return nil
	}

	return fmt.Errorf("%+v is not a valid UpdateListingRequestItemDimensionsUnit", value)
}

// NewUpdateListingRequestItemDimensionsUnitFromValue returns a pointer to a valid UpdateListingRequestItemDimensionsUnit
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUpdateListingRequestItemDimensionsUnitFromValue(v string) (*UpdateListingRequestItemDimensionsUnit, error) {
	ev := UpdateListingRequestItemDimensionsUnit(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UpdateListingRequestItemDimensionsUnit: valid values are %v", v, AllowedUpdateListingRequestItemDimensionsUnitEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UpdateListingRequestItemDimensionsUnit) IsValid() bool {
	for _, existing := range AllowedUpdateListingRequestItemDimensionsUnitEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to updateListing_request_item_dimensions_unit value
func (v UpdateListingRequestItemDimensionsUnit) Ptr() *UpdateListingRequestItemDimensionsUnit {
	return &v
}

type NullableUpdateListingRequestItemDimensionsUnit struct {
	value *UpdateListingRequestItemDimensionsUnit
	isSet bool
}

func (v NullableUpdateListingRequestItemDimensionsUnit) Get() *UpdateListingRequestItemDimensionsUnit {
	return v.value
}

func (v *NullableUpdateListingRequestItemDimensionsUnit) Set(val *UpdateListingRequestItemDimensionsUnit) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateListingRequestItemDimensionsUnit) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateListingRequestItemDimensionsUnit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateListingRequestItemDimensionsUnit(val *UpdateListingRequestItemDimensionsUnit) *NullableUpdateListingRequestItemDimensionsUnit {
	return &NullableUpdateListingRequestItemDimensionsUnit{value: val, isSet: true}
}

func (v NullableUpdateListingRequestItemDimensionsUnit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateListingRequestItemDimensionsUnit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
