/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2026 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
)

// checks if the EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner{}

// EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner struct for EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner
type EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner struct {
	OptionId             NullableInt64 `json:"option_id"`
	Label                string        `json:"label"`
	AdditionalProperties map[string]interface{}
}

type _EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner

// NewEtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner instantiates a new EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner(optionId NullableInt64, label string) *EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner {
	this := EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner{}
	this.OptionId = optionId
	this.Label = label
	return &this
}

// NewEtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInnerWithDefaults instantiates a new EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInnerWithDefaults() *EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner {
	this := EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner{}
	return &this
}

// GetOptionId returns the OptionId field value
// If the value is explicit nil, the zero value for int64 will be returned
func (o *EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) GetOptionId() int64 {
	if o == nil || o.OptionId.Get() == nil {
		var ret int64
		return ret
	}

	return *o.OptionId.Get()
}

// GetOptionIdOk returns a tuple with the OptionId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) GetOptionIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.OptionId.Get(), o.OptionId.IsSet()
}

// SetOptionId sets field value
func (o *EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) SetOptionId(v int64) {
	o.OptionId.Set(&v)
}

// GetLabel returns the Label field value
func (o *EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) SetLabel(v string) {
	o.Label = v
}

func (o EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["option_id"] = o.OptionId.Get()
	toSerialize["label"] = o.Label

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableEtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner struct {
	value *EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner
	isSet bool
}

func (v NullableEtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) Get() *EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner {
	return v.value
}

func (v *NullableEtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) Set(val *EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableEtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableEtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner(val *EtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) *NullableEtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner {
	return &NullableEtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner{value: val, isSet: true}
}

func (v NullableEtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEtsyModulesListingPersonalizationApiResourcesOpenApiPersonalizationQuestionOptionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
