/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2026 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
	"fmt"
	"strings"
	"unicode"
)

// ShopListingWhoMade An enumerated string indicating who made the product. Helps buyers locate the listing under the Handmade heading. Requires 'is_supply' and 'when_made'.
type ShopListingWhoMade string

// List of ShopListing_who_made
const (
	SHOPLISTINGWHOMADE_I_DID        ShopListingWhoMade = "i_did"
	SHOPLISTINGWHOMADE_SOMEONE_ELSE ShopListingWhoMade = "someone_else"
	SHOPLISTINGWHOMADE_COLLECTIVE   ShopListingWhoMade = "collective"
)

// All allowed values of ShopListingWhoMade enum
var AllowedShopListingWhoMadeEnumValues = []ShopListingWhoMade{
	"i_did",
	"someone_else",
	"collective",
}

var AllowedShopListingWhoMadeEnumValuesValidator = map[interface{}]struct{}{
	ShopListingWhoMade("i_did").Ptr().generateNormalizedEnum():        struct{}{},
	ShopListingWhoMade("someone_else").Ptr().generateNormalizedEnum(): struct{}{},
	ShopListingWhoMade("collective").Ptr().generateNormalizedEnum():   struct{}{},
}

func (v *ShopListingWhoMade) generateNormalizedEnum() any {
	if v == nil {
		return nil
	}

	s := *v
	var sb strings.Builder
	sb.Grow(len(s) + 2)     // Preallocate memory for efficiency
	var prevUnderscore bool // Track consecutive underscores
	for i, r := range s {
		switch {
		case unicode.IsUpper(r):
			// Add an underscore if:
			// 1. Not the first character
			// 2. Previous character is NOT uppercase (to handle acronyms like "HTTPRequest")
			// 3. Next character is lowercase (to avoid splitting acronyms)
			if i > 0 && (!unicode.IsUpper(rune(s[i-1])) || (i+1 < len(s) && unicode.IsLower(rune(s[i+1])))) {
				sb.WriteByte('_')
			}
			sb.WriteRune(unicode.ToLower(r))
			prevUnderscore = false

		case unicode.IsSpace(r) || r == '-' || r == '_': // Convert spaces, dashes, and underscores to `_`
			if !prevUnderscore { // Avoid consecutive `_`
				sb.WriteByte('_')
				prevUnderscore = true
			}

		case unicode.IsLetter(r) || unicode.IsDigit(r): // Keep letters and numbers
			sb.WriteRune(r)
			prevUnderscore = false

		default:
			// Ignore symbols (e.g., `@#$%&*!`)
		}
	}

	// Trim leading/trailing underscores
	return strings.Trim(sb.String(), "_")

}

func (v *ShopListingWhoMade) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ShopListingWhoMade(value)
	if _, existing := AllowedShopListingWhoMadeEnumValuesValidator[enumTypeValue.Ptr().generateNormalizedEnum()]; existing {
		*v = enumTypeValue
		return nil
	}

	return fmt.Errorf("%+v is not a valid ShopListingWhoMade", value)
}

// NewShopListingWhoMadeFromValue returns a pointer to a valid ShopListingWhoMade
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewShopListingWhoMadeFromValue(v string) (*ShopListingWhoMade, error) {
	ev := ShopListingWhoMade(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ShopListingWhoMade: valid values are %v", v, AllowedShopListingWhoMadeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ShopListingWhoMade) IsValid() bool {
	for _, existing := range AllowedShopListingWhoMadeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ShopListing_who_made value
func (v ShopListingWhoMade) Ptr() *ShopListingWhoMade {
	return &v
}

type NullableShopListingWhoMade struct {
	value *ShopListingWhoMade
	isSet bool
}

func (v NullableShopListingWhoMade) Get() *ShopListingWhoMade {
	return v.value
}

func (v *NullableShopListingWhoMade) Set(val *ShopListingWhoMade) {
	v.value = val
	v.isSet = true
}

func (v NullableShopListingWhoMade) IsSet() bool {
	return v.isSet
}

func (v *NullableShopListingWhoMade) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShopListingWhoMade(val *ShopListingWhoMade) *NullableShopListingWhoMade {
	return &NullableShopListingWhoMade{value: val, isSet: true}
}

func (v NullableShopListingWhoMade) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShopListingWhoMade) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
