/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2024 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
	"fmt"
)

// UpdateListingRequestItemWeightUnit A string defining the units used to measure the weight of the product. Default value is null.
type UpdateListingRequestItemWeightUnit string

// List of updateListing_request_item_weight_unit
const (
	UPDATELISTINGREQUESTITEMWEIGHTUNIT_EMPTY UpdateListingRequestItemWeightUnit = ""
	UPDATELISTINGREQUESTITEMWEIGHTUNIT_OZ    UpdateListingRequestItemWeightUnit = "oz"
	UPDATELISTINGREQUESTITEMWEIGHTUNIT_LB    UpdateListingRequestItemWeightUnit = "lb"
	UPDATELISTINGREQUESTITEMWEIGHTUNIT_G     UpdateListingRequestItemWeightUnit = "g"
	UPDATELISTINGREQUESTITEMWEIGHTUNIT_KG    UpdateListingRequestItemWeightUnit = "kg"
)

// All allowed values of UpdateListingRequestItemWeightUnit enum
var AllowedUpdateListingRequestItemWeightUnitEnumValues = []UpdateListingRequestItemWeightUnit{
	"",
	"oz",
	"lb",
	"g",
	"kg",
}

func (v *UpdateListingRequestItemWeightUnit) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UpdateListingRequestItemWeightUnit(value)
	for _, existing := range AllowedUpdateListingRequestItemWeightUnitEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UpdateListingRequestItemWeightUnit", value)
}

// NewUpdateListingRequestItemWeightUnitFromValue returns a pointer to a valid UpdateListingRequestItemWeightUnit
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUpdateListingRequestItemWeightUnitFromValue(v string) (*UpdateListingRequestItemWeightUnit, error) {
	ev := UpdateListingRequestItemWeightUnit(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UpdateListingRequestItemWeightUnit: valid values are %v", v, AllowedUpdateListingRequestItemWeightUnitEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UpdateListingRequestItemWeightUnit) IsValid() bool {
	for _, existing := range AllowedUpdateListingRequestItemWeightUnitEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to updateListing_request_item_weight_unit value
func (v UpdateListingRequestItemWeightUnit) Ptr() *UpdateListingRequestItemWeightUnit {
	return &v
}

type NullableUpdateListingRequestItemWeightUnit struct {
	value *UpdateListingRequestItemWeightUnit
	isSet bool
}

func (v NullableUpdateListingRequestItemWeightUnit) Get() *UpdateListingRequestItemWeightUnit {
	return v.value
}

func (v *NullableUpdateListingRequestItemWeightUnit) Set(val *UpdateListingRequestItemWeightUnit) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateListingRequestItemWeightUnit) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateListingRequestItemWeightUnit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateListingRequestItemWeightUnit(val *UpdateListingRequestItemWeightUnit) *NullableUpdateListingRequestItemWeightUnit {
	return &NullableUpdateListingRequestItemWeightUnit{value: val, isSet: true}
}

func (v NullableUpdateListingRequestItemWeightUnit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateListingRequestItemWeightUnit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
