/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2026 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
)

// checks if the UpdateShopReadinessStateDefinitionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateShopReadinessStateDefinitionRequest{}

// UpdateShopReadinessStateDefinitionRequest struct for UpdateShopReadinessStateDefinitionRequest
type UpdateShopReadinessStateDefinitionRequest struct {
	ReadinessState *CreateShopReadinessStateDefinitionRequestReadinessState `json:"readiness_state,omitempty"`
	// The minimum number of days or weeks for processing a specific product.
	MinProcessingTime *int64 `json:"min_processing_time,omitempty"`
	// The maximum number of days or weeks for processing a specific product.
	MaxProcessingTime    *int64                                                       `json:"max_processing_time,omitempty"`
	ProcessingTimeUnit   *CreateShopReadinessStateDefinitionRequestProcessingTimeUnit `json:"processing_time_unit,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateShopReadinessStateDefinitionRequest UpdateShopReadinessStateDefinitionRequest

// NewUpdateShopReadinessStateDefinitionRequest instantiates a new UpdateShopReadinessStateDefinitionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateShopReadinessStateDefinitionRequest() *UpdateShopReadinessStateDefinitionRequest {
	this := UpdateShopReadinessStateDefinitionRequest{}
	var processingTimeUnit CreateShopReadinessStateDefinitionRequestProcessingTimeUnit = CREATESHOPREADINESSSTATEDEFINITIONREQUESTPROCESSINGTIMEUNIT_DAYS
	this.ProcessingTimeUnit = &processingTimeUnit
	return &this
}

// NewUpdateShopReadinessStateDefinitionRequestWithDefaults instantiates a new UpdateShopReadinessStateDefinitionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateShopReadinessStateDefinitionRequestWithDefaults() *UpdateShopReadinessStateDefinitionRequest {
	this := UpdateShopReadinessStateDefinitionRequest{}
	var processingTimeUnit CreateShopReadinessStateDefinitionRequestProcessingTimeUnit = CREATESHOPREADINESSSTATEDEFINITIONREQUESTPROCESSINGTIMEUNIT_DAYS
	this.ProcessingTimeUnit = &processingTimeUnit
	return &this
}

// GetReadinessState returns the ReadinessState field value if set, zero value otherwise.
func (o *UpdateShopReadinessStateDefinitionRequest) GetReadinessState() CreateShopReadinessStateDefinitionRequestReadinessState {
	if o == nil || IsNil(o.ReadinessState) {
		var ret CreateShopReadinessStateDefinitionRequestReadinessState
		return ret
	}
	return *o.ReadinessState
}

// GetReadinessStateOk returns a tuple with the ReadinessState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopReadinessStateDefinitionRequest) GetReadinessStateOk() (*CreateShopReadinessStateDefinitionRequestReadinessState, bool) {
	if o == nil || IsNil(o.ReadinessState) {
		return nil, false
	}
	return o.ReadinessState, true
}

// HasReadinessState returns a boolean if a field has been set.
func (o *UpdateShopReadinessStateDefinitionRequest) HasReadinessState() bool {
	if o != nil && !IsNil(o.ReadinessState) {
		return true
	}

	return false
}

// SetReadinessState gets a reference to the given CreateShopReadinessStateDefinitionRequestReadinessState and assigns it to the ReadinessState field.
func (o *UpdateShopReadinessStateDefinitionRequest) SetReadinessState(v CreateShopReadinessStateDefinitionRequestReadinessState) {
	o.ReadinessState = &v
}

// GetMinProcessingTime returns the MinProcessingTime field value if set, zero value otherwise.
func (o *UpdateShopReadinessStateDefinitionRequest) GetMinProcessingTime() int64 {
	if o == nil || IsNil(o.MinProcessingTime) {
		var ret int64
		return ret
	}
	return *o.MinProcessingTime
}

// GetMinProcessingTimeOk returns a tuple with the MinProcessingTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopReadinessStateDefinitionRequest) GetMinProcessingTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.MinProcessingTime) {
		return nil, false
	}
	return o.MinProcessingTime, true
}

// HasMinProcessingTime returns a boolean if a field has been set.
func (o *UpdateShopReadinessStateDefinitionRequest) HasMinProcessingTime() bool {
	if o != nil && !IsNil(o.MinProcessingTime) {
		return true
	}

	return false
}

// SetMinProcessingTime gets a reference to the given int64 and assigns it to the MinProcessingTime field.
func (o *UpdateShopReadinessStateDefinitionRequest) SetMinProcessingTime(v int64) {
	o.MinProcessingTime = &v
}

// GetMaxProcessingTime returns the MaxProcessingTime field value if set, zero value otherwise.
func (o *UpdateShopReadinessStateDefinitionRequest) GetMaxProcessingTime() int64 {
	if o == nil || IsNil(o.MaxProcessingTime) {
		var ret int64
		return ret
	}
	return *o.MaxProcessingTime
}

// GetMaxProcessingTimeOk returns a tuple with the MaxProcessingTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopReadinessStateDefinitionRequest) GetMaxProcessingTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxProcessingTime) {
		return nil, false
	}
	return o.MaxProcessingTime, true
}

// HasMaxProcessingTime returns a boolean if a field has been set.
func (o *UpdateShopReadinessStateDefinitionRequest) HasMaxProcessingTime() bool {
	if o != nil && !IsNil(o.MaxProcessingTime) {
		return true
	}

	return false
}

// SetMaxProcessingTime gets a reference to the given int64 and assigns it to the MaxProcessingTime field.
func (o *UpdateShopReadinessStateDefinitionRequest) SetMaxProcessingTime(v int64) {
	o.MaxProcessingTime = &v
}

// GetProcessingTimeUnit returns the ProcessingTimeUnit field value if set, zero value otherwise.
func (o *UpdateShopReadinessStateDefinitionRequest) GetProcessingTimeUnit() CreateShopReadinessStateDefinitionRequestProcessingTimeUnit {
	if o == nil || IsNil(o.ProcessingTimeUnit) {
		var ret CreateShopReadinessStateDefinitionRequestProcessingTimeUnit
		return ret
	}
	return *o.ProcessingTimeUnit
}

// GetProcessingTimeUnitOk returns a tuple with the ProcessingTimeUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopReadinessStateDefinitionRequest) GetProcessingTimeUnitOk() (*CreateShopReadinessStateDefinitionRequestProcessingTimeUnit, bool) {
	if o == nil || IsNil(o.ProcessingTimeUnit) {
		return nil, false
	}
	return o.ProcessingTimeUnit, true
}

// HasProcessingTimeUnit returns a boolean if a field has been set.
func (o *UpdateShopReadinessStateDefinitionRequest) HasProcessingTimeUnit() bool {
	if o != nil && !IsNil(o.ProcessingTimeUnit) {
		return true
	}

	return false
}

// SetProcessingTimeUnit gets a reference to the given CreateShopReadinessStateDefinitionRequestProcessingTimeUnit and assigns it to the ProcessingTimeUnit field.
func (o *UpdateShopReadinessStateDefinitionRequest) SetProcessingTimeUnit(v CreateShopReadinessStateDefinitionRequestProcessingTimeUnit) {
	o.ProcessingTimeUnit = &v
}

func (o UpdateShopReadinessStateDefinitionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateShopReadinessStateDefinitionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ReadinessState) {
		toSerialize["readiness_state"] = o.ReadinessState
	}
	if !IsNil(o.MinProcessingTime) {
		toSerialize["min_processing_time"] = o.MinProcessingTime
	}
	if !IsNil(o.MaxProcessingTime) {
		toSerialize["max_processing_time"] = o.MaxProcessingTime
	}
	if !IsNil(o.ProcessingTimeUnit) {
		toSerialize["processing_time_unit"] = o.ProcessingTimeUnit
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateShopReadinessStateDefinitionRequest struct {
	value *UpdateShopReadinessStateDefinitionRequest
	isSet bool
}

func (v NullableUpdateShopReadinessStateDefinitionRequest) Get() *UpdateShopReadinessStateDefinitionRequest {
	return v.value
}

func (v *NullableUpdateShopReadinessStateDefinitionRequest) Set(val *UpdateShopReadinessStateDefinitionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateShopReadinessStateDefinitionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateShopReadinessStateDefinitionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateShopReadinessStateDefinitionRequest(val *UpdateShopReadinessStateDefinitionRequest) *NullableUpdateShopReadinessStateDefinitionRequest {
	return &NullableUpdateShopReadinessStateDefinitionRequest{value: val, isSet: true}
}

func (v NullableUpdateShopReadinessStateDefinitionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateShopReadinessStateDefinitionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
