/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2026 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
	"fmt"
	"strings"
	"unicode"
)

// UpdateListingRequestType An enumerated type string that indicates whether the listing is physical or a digital download.
type UpdateListingRequestType string

// List of updateListing_request_type
const (
	UPDATELISTINGREQUESTTYPE_PHYSICAL UpdateListingRequestType = "physical"
	UPDATELISTINGREQUESTTYPE_DOWNLOAD UpdateListingRequestType = "download"
	UPDATELISTINGREQUESTTYPE_BOTH     UpdateListingRequestType = "both"
)

// All allowed values of UpdateListingRequestType enum
var AllowedUpdateListingRequestTypeEnumValues = []UpdateListingRequestType{
	"physical",
	"download",
	"both",
}

var AllowedUpdateListingRequestTypeEnumValuesValidator = map[interface{}]struct{}{
	UpdateListingRequestType("physical").Ptr().generateNormalizedEnum(): struct{}{},
	UpdateListingRequestType("download").Ptr().generateNormalizedEnum(): struct{}{},
	UpdateListingRequestType("both").Ptr().generateNormalizedEnum():     struct{}{},
}

func (v *UpdateListingRequestType) generateNormalizedEnum() any {
	if v == nil {
		return nil
	}

	s := *v
	var sb strings.Builder
	sb.Grow(len(s) + 2)     // Preallocate memory for efficiency
	var prevUnderscore bool // Track consecutive underscores
	for i, r := range s {
		switch {
		case unicode.IsUpper(r):
			// Add an underscore if:
			// 1. Not the first character
			// 2. Previous character is NOT uppercase (to handle acronyms like "HTTPRequest")
			// 3. Next character is lowercase (to avoid splitting acronyms)
			if i > 0 && (!unicode.IsUpper(rune(s[i-1])) || (i+1 < len(s) && unicode.IsLower(rune(s[i+1])))) {
				sb.WriteByte('_')
			}
			sb.WriteRune(unicode.ToLower(r))
			prevUnderscore = false

		case unicode.IsSpace(r) || r == '-' || r == '_': // Convert spaces, dashes, and underscores to `_`
			if !prevUnderscore { // Avoid consecutive `_`
				sb.WriteByte('_')
				prevUnderscore = true
			}

		case unicode.IsLetter(r) || unicode.IsDigit(r): // Keep letters and numbers
			sb.WriteRune(r)
			prevUnderscore = false

		default:
			// Ignore symbols (e.g., `@#$%&*!`)
		}
	}

	// Trim leading/trailing underscores
	return strings.Trim(sb.String(), "_")

}

func (v *UpdateListingRequestType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UpdateListingRequestType(value)
	if _, existing := AllowedUpdateListingRequestTypeEnumValuesValidator[enumTypeValue.Ptr().generateNormalizedEnum()]; existing {
		*v = enumTypeValue
		return nil
	}

	return fmt.Errorf("%+v is not a valid UpdateListingRequestType", value)
}

// NewUpdateListingRequestTypeFromValue returns a pointer to a valid UpdateListingRequestType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUpdateListingRequestTypeFromValue(v string) (*UpdateListingRequestType, error) {
	ev := UpdateListingRequestType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UpdateListingRequestType: valid values are %v", v, AllowedUpdateListingRequestTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UpdateListingRequestType) IsValid() bool {
	for _, existing := range AllowedUpdateListingRequestTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to updateListing_request_type value
func (v UpdateListingRequestType) Ptr() *UpdateListingRequestType {
	return &v
}

type NullableUpdateListingRequestType struct {
	value *UpdateListingRequestType
	isSet bool
}

func (v NullableUpdateListingRequestType) Get() *UpdateListingRequestType {
	return v.value
}

func (v *NullableUpdateListingRequestType) Set(val *UpdateListingRequestType) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateListingRequestType) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateListingRequestType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateListingRequestType(val *UpdateListingRequestType) *NullableUpdateListingRequestType {
	return &NullableUpdateListingRequestType{value: val, isSet: true}
}

func (v NullableUpdateListingRequestType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateListingRequestType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
