/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2024 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
)

// checks if the UpdateShopShippingProfileRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateShopShippingProfileRequest{}

// UpdateShopShippingProfileRequest struct for UpdateShopShippingProfileRequest
type UpdateShopShippingProfileRequest struct {
	// The name string of this shipping profile.
	Title *string `json:"title,omitempty"`
	// The ISO code of the country from which the listing ships.
	OriginCountryIso *string `json:"origin_country_iso,omitempty"`
	// The minimum time required to process to ship listings with this shipping profile.
	MinProcessingTime *int64 `json:"min_processing_time,omitempty"`
	// The maximum processing time the listing needs to ship.
	MaxProcessingTime  *int64                                              `json:"max_processing_time,omitempty"`
	ProcessingTimeUnit *CreateShopShippingProfileRequestProcessingTimeUnit `json:"processing_time_unit,omitempty"`
	// The postal code string (not necessarily a number) for the location from which the listing ships. Required if the `origin_country_iso` supports postal codes. See the [Fulfillment Tutorial docs](https://developer.etsy.com/documentation/tutorials/fulfillment/#countries-requiring-postal-codes) for more info
	OriginPostalCode     *string `json:"origin_postal_code,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateShopShippingProfileRequest UpdateShopShippingProfileRequest

// NewUpdateShopShippingProfileRequest instantiates a new UpdateShopShippingProfileRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateShopShippingProfileRequest() *UpdateShopShippingProfileRequest {
	this := UpdateShopShippingProfileRequest{}
	var processingTimeUnit CreateShopShippingProfileRequestProcessingTimeUnit = CREATESHOPSHIPPINGPROFILEREQUESTPROCESSINGTIMEUNIT_BUSINESS_DAYS
	this.ProcessingTimeUnit = &processingTimeUnit
	return &this
}

// NewUpdateShopShippingProfileRequestWithDefaults instantiates a new UpdateShopShippingProfileRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateShopShippingProfileRequestWithDefaults() *UpdateShopShippingProfileRequest {
	this := UpdateShopShippingProfileRequest{}
	var processingTimeUnit CreateShopShippingProfileRequestProcessingTimeUnit = CREATESHOPSHIPPINGPROFILEREQUESTPROCESSINGTIMEUNIT_BUSINESS_DAYS
	this.ProcessingTimeUnit = &processingTimeUnit
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *UpdateShopShippingProfileRequest) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopShippingProfileRequest) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *UpdateShopShippingProfileRequest) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *UpdateShopShippingProfileRequest) SetTitle(v string) {
	o.Title = &v
}

// GetOriginCountryIso returns the OriginCountryIso field value if set, zero value otherwise.
func (o *UpdateShopShippingProfileRequest) GetOriginCountryIso() string {
	if o == nil || IsNil(o.OriginCountryIso) {
		var ret string
		return ret
	}
	return *o.OriginCountryIso
}

// GetOriginCountryIsoOk returns a tuple with the OriginCountryIso field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopShippingProfileRequest) GetOriginCountryIsoOk() (*string, bool) {
	if o == nil || IsNil(o.OriginCountryIso) {
		return nil, false
	}
	return o.OriginCountryIso, true
}

// HasOriginCountryIso returns a boolean if a field has been set.
func (o *UpdateShopShippingProfileRequest) HasOriginCountryIso() bool {
	if o != nil && !IsNil(o.OriginCountryIso) {
		return true
	}

	return false
}

// SetOriginCountryIso gets a reference to the given string and assigns it to the OriginCountryIso field.
func (o *UpdateShopShippingProfileRequest) SetOriginCountryIso(v string) {
	o.OriginCountryIso = &v
}

// GetMinProcessingTime returns the MinProcessingTime field value if set, zero value otherwise.
func (o *UpdateShopShippingProfileRequest) GetMinProcessingTime() int64 {
	if o == nil || IsNil(o.MinProcessingTime) {
		var ret int64
		return ret
	}
	return *o.MinProcessingTime
}

// GetMinProcessingTimeOk returns a tuple with the MinProcessingTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopShippingProfileRequest) GetMinProcessingTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.MinProcessingTime) {
		return nil, false
	}
	return o.MinProcessingTime, true
}

// HasMinProcessingTime returns a boolean if a field has been set.
func (o *UpdateShopShippingProfileRequest) HasMinProcessingTime() bool {
	if o != nil && !IsNil(o.MinProcessingTime) {
		return true
	}

	return false
}

// SetMinProcessingTime gets a reference to the given int64 and assigns it to the MinProcessingTime field.
func (o *UpdateShopShippingProfileRequest) SetMinProcessingTime(v int64) {
	o.MinProcessingTime = &v
}

// GetMaxProcessingTime returns the MaxProcessingTime field value if set, zero value otherwise.
func (o *UpdateShopShippingProfileRequest) GetMaxProcessingTime() int64 {
	if o == nil || IsNil(o.MaxProcessingTime) {
		var ret int64
		return ret
	}
	return *o.MaxProcessingTime
}

// GetMaxProcessingTimeOk returns a tuple with the MaxProcessingTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopShippingProfileRequest) GetMaxProcessingTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxProcessingTime) {
		return nil, false
	}
	return o.MaxProcessingTime, true
}

// HasMaxProcessingTime returns a boolean if a field has been set.
func (o *UpdateShopShippingProfileRequest) HasMaxProcessingTime() bool {
	if o != nil && !IsNil(o.MaxProcessingTime) {
		return true
	}

	return false
}

// SetMaxProcessingTime gets a reference to the given int64 and assigns it to the MaxProcessingTime field.
func (o *UpdateShopShippingProfileRequest) SetMaxProcessingTime(v int64) {
	o.MaxProcessingTime = &v
}

// GetProcessingTimeUnit returns the ProcessingTimeUnit field value if set, zero value otherwise.
func (o *UpdateShopShippingProfileRequest) GetProcessingTimeUnit() CreateShopShippingProfileRequestProcessingTimeUnit {
	if o == nil || IsNil(o.ProcessingTimeUnit) {
		var ret CreateShopShippingProfileRequestProcessingTimeUnit
		return ret
	}
	return *o.ProcessingTimeUnit
}

// GetProcessingTimeUnitOk returns a tuple with the ProcessingTimeUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopShippingProfileRequest) GetProcessingTimeUnitOk() (*CreateShopShippingProfileRequestProcessingTimeUnit, bool) {
	if o == nil || IsNil(o.ProcessingTimeUnit) {
		return nil, false
	}
	return o.ProcessingTimeUnit, true
}

// HasProcessingTimeUnit returns a boolean if a field has been set.
func (o *UpdateShopShippingProfileRequest) HasProcessingTimeUnit() bool {
	if o != nil && !IsNil(o.ProcessingTimeUnit) {
		return true
	}

	return false
}

// SetProcessingTimeUnit gets a reference to the given CreateShopShippingProfileRequestProcessingTimeUnit and assigns it to the ProcessingTimeUnit field.
func (o *UpdateShopShippingProfileRequest) SetProcessingTimeUnit(v CreateShopShippingProfileRequestProcessingTimeUnit) {
	o.ProcessingTimeUnit = &v
}

// GetOriginPostalCode returns the OriginPostalCode field value if set, zero value otherwise.
func (o *UpdateShopShippingProfileRequest) GetOriginPostalCode() string {
	if o == nil || IsNil(o.OriginPostalCode) {
		var ret string
		return ret
	}
	return *o.OriginPostalCode
}

// GetOriginPostalCodeOk returns a tuple with the OriginPostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopShippingProfileRequest) GetOriginPostalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.OriginPostalCode) {
		return nil, false
	}
	return o.OriginPostalCode, true
}

// HasOriginPostalCode returns a boolean if a field has been set.
func (o *UpdateShopShippingProfileRequest) HasOriginPostalCode() bool {
	if o != nil && !IsNil(o.OriginPostalCode) {
		return true
	}

	return false
}

// SetOriginPostalCode gets a reference to the given string and assigns it to the OriginPostalCode field.
func (o *UpdateShopShippingProfileRequest) SetOriginPostalCode(v string) {
	o.OriginPostalCode = &v
}

func (o UpdateShopShippingProfileRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateShopShippingProfileRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.OriginCountryIso) {
		toSerialize["origin_country_iso"] = o.OriginCountryIso
	}
	if !IsNil(o.MinProcessingTime) {
		toSerialize["min_processing_time"] = o.MinProcessingTime
	}
	if !IsNil(o.MaxProcessingTime) {
		toSerialize["max_processing_time"] = o.MaxProcessingTime
	}
	if !IsNil(o.ProcessingTimeUnit) {
		toSerialize["processing_time_unit"] = o.ProcessingTimeUnit
	}
	if !IsNil(o.OriginPostalCode) {
		toSerialize["origin_postal_code"] = o.OriginPostalCode
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateShopShippingProfileRequest struct {
	value *UpdateShopShippingProfileRequest
	isSet bool
}

func (v NullableUpdateShopShippingProfileRequest) Get() *UpdateShopShippingProfileRequest {
	return v.value
}

func (v *NullableUpdateShopShippingProfileRequest) Set(val *UpdateShopShippingProfileRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateShopShippingProfileRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateShopShippingProfileRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateShopShippingProfileRequest(val *UpdateShopShippingProfileRequest) *NullableUpdateShopShippingProfileRequest {
	return &NullableUpdateShopShippingProfileRequest{value: val, isSet: true}
}

func (v NullableUpdateShopShippingProfileRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateShopShippingProfileRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
