/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2026 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
)

// checks if the ShopProcessingProfiles type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShopProcessingProfiles{}

// ShopProcessingProfiles Represents several ProcessingProfiles.
type ShopProcessingProfiles struct {
	Count                *int64                  `json:"count,omitempty"`
	Results              []ShopProcessingProfile `json:"results,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ShopProcessingProfiles ShopProcessingProfiles

// NewShopProcessingProfiles instantiates a new ShopProcessingProfiles object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShopProcessingProfiles() *ShopProcessingProfiles {
	this := ShopProcessingProfiles{}
	return &this
}

// NewShopProcessingProfilesWithDefaults instantiates a new ShopProcessingProfiles object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShopProcessingProfilesWithDefaults() *ShopProcessingProfiles {
	this := ShopProcessingProfiles{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ShopProcessingProfiles) GetCount() int64 {
	if o == nil || IsNil(o.Count) {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShopProcessingProfiles) GetCountOk() (*int64, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ShopProcessingProfiles) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *ShopProcessingProfiles) SetCount(v int64) {
	o.Count = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *ShopProcessingProfiles) GetResults() []ShopProcessingProfile {
	if o == nil || IsNil(o.Results) {
		var ret []ShopProcessingProfile
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShopProcessingProfiles) GetResultsOk() ([]ShopProcessingProfile, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *ShopProcessingProfiles) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []ShopProcessingProfile and assigns it to the Results field.
func (o *ShopProcessingProfiles) SetResults(v []ShopProcessingProfile) {
	o.Results = v
}

func (o ShopProcessingProfiles) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShopProcessingProfiles) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableShopProcessingProfiles struct {
	value *ShopProcessingProfiles
	isSet bool
}

func (v NullableShopProcessingProfiles) Get() *ShopProcessingProfiles {
	return v.value
}

func (v *NullableShopProcessingProfiles) Set(val *ShopProcessingProfiles) {
	v.value = val
	v.isSet = true
}

func (v NullableShopProcessingProfiles) IsSet() bool {
	return v.isSet
}

func (v *NullableShopProcessingProfiles) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShopProcessingProfiles(val *ShopProcessingProfiles) *NullableShopProcessingProfiles {
	return &NullableShopProcessingProfiles{value: val, isSet: true}
}

func (v NullableShopProcessingProfiles) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShopProcessingProfiles) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
