/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2026 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
)

// checks if the UpdateListingPropertyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateListingPropertyRequest{}

// UpdateListingPropertyRequest struct for UpdateListingPropertyRequest
type UpdateListingPropertyRequest struct {
	// An array of unique IDs of multiple Etsy [listing property](/documentation/reference#operation/getListingProperties) values. For example, if your listing offers different sizes of a product, then the value ID list contains value IDs for each size.
	ValueIds []int64 `json:"value_ids"`
	// An array of value strings for multiple Etsy [listing property](/documentation/reference#operation/getListingProperties) values. For example, if your listing offers different colored products, then the values array contains the color strings for each color. Note: parenthesis characters (`(` and `)`) are not allowed.
	Values []string `json:"values"`
	// The numeric ID of a single Etsy.com measurement scale. For example, for shoe size, there are three `scale_id`s available - `UK`, `US/Canada`, and `EU`, where `US/Canada` has `scale_id` 19.
	ScaleId              *int64 `json:"scale_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateListingPropertyRequest UpdateListingPropertyRequest

// NewUpdateListingPropertyRequest instantiates a new UpdateListingPropertyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateListingPropertyRequest(valueIds []int64, values []string) *UpdateListingPropertyRequest {
	this := UpdateListingPropertyRequest{}
	this.ValueIds = valueIds
	this.Values = values
	return &this
}

// NewUpdateListingPropertyRequestWithDefaults instantiates a new UpdateListingPropertyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateListingPropertyRequestWithDefaults() *UpdateListingPropertyRequest {
	this := UpdateListingPropertyRequest{}
	return &this
}

// GetValueIds returns the ValueIds field value
func (o *UpdateListingPropertyRequest) GetValueIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.ValueIds
}

// GetValueIdsOk returns a tuple with the ValueIds field value
// and a boolean to check if the value has been set.
func (o *UpdateListingPropertyRequest) GetValueIdsOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ValueIds, true
}

// SetValueIds sets field value
func (o *UpdateListingPropertyRequest) SetValueIds(v []int64) {
	o.ValueIds = v
}

// GetValues returns the Values field value
func (o *UpdateListingPropertyRequest) GetValues() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *UpdateListingPropertyRequest) GetValuesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Values, true
}

// SetValues sets field value
func (o *UpdateListingPropertyRequest) SetValues(v []string) {
	o.Values = v
}

// GetScaleId returns the ScaleId field value if set, zero value otherwise.
func (o *UpdateListingPropertyRequest) GetScaleId() int64 {
	if o == nil || IsNil(o.ScaleId) {
		var ret int64
		return ret
	}
	return *o.ScaleId
}

// GetScaleIdOk returns a tuple with the ScaleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateListingPropertyRequest) GetScaleIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ScaleId) {
		return nil, false
	}
	return o.ScaleId, true
}

// HasScaleId returns a boolean if a field has been set.
func (o *UpdateListingPropertyRequest) HasScaleId() bool {
	if o != nil && !IsNil(o.ScaleId) {
		return true
	}

	return false
}

// SetScaleId gets a reference to the given int64 and assigns it to the ScaleId field.
func (o *UpdateListingPropertyRequest) SetScaleId(v int64) {
	o.ScaleId = &v
}

func (o UpdateListingPropertyRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateListingPropertyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value_ids"] = o.ValueIds
	toSerialize["values"] = o.Values
	if !IsNil(o.ScaleId) {
		toSerialize["scale_id"] = o.ScaleId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateListingPropertyRequest struct {
	value *UpdateListingPropertyRequest
	isSet bool
}

func (v NullableUpdateListingPropertyRequest) Get() *UpdateListingPropertyRequest {
	return v.value
}

func (v *NullableUpdateListingPropertyRequest) Set(val *UpdateListingPropertyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateListingPropertyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateListingPropertyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateListingPropertyRequest(val *UpdateListingPropertyRequest) *NullableUpdateListingPropertyRequest {
	return &NullableUpdateListingPropertyRequest{value: val, isSet: true}
}

func (v NullableUpdateListingPropertyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateListingPropertyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
