/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2026 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
)

// checks if the CreateReceiptShipmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateReceiptShipmentRequest{}

// CreateReceiptShipmentRequest struct for CreateReceiptShipmentRequest
type CreateReceiptShipmentRequest struct {
	// The tracking code for this receipt.
	TrackingCode *string `json:"tracking_code,omitempty"`
	// The carrier name for this receipt.
	CarrierName *string `json:"carrier_name,omitempty"`
	// If true, the shipping notification will be sent to the seller as well
	SendBcc *bool `json:"send_bcc,omitempty"`
	// Message to include in notification to the buyer.
	NoteToBuyer          *string `json:"note_to_buyer,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateReceiptShipmentRequest CreateReceiptShipmentRequest

// NewCreateReceiptShipmentRequest instantiates a new CreateReceiptShipmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateReceiptShipmentRequest() *CreateReceiptShipmentRequest {
	this := CreateReceiptShipmentRequest{}
	return &this
}

// NewCreateReceiptShipmentRequestWithDefaults instantiates a new CreateReceiptShipmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateReceiptShipmentRequestWithDefaults() *CreateReceiptShipmentRequest {
	this := CreateReceiptShipmentRequest{}
	return &this
}

// GetTrackingCode returns the TrackingCode field value if set, zero value otherwise.
func (o *CreateReceiptShipmentRequest) GetTrackingCode() string {
	if o == nil || IsNil(o.TrackingCode) {
		var ret string
		return ret
	}
	return *o.TrackingCode
}

// GetTrackingCodeOk returns a tuple with the TrackingCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReceiptShipmentRequest) GetTrackingCodeOk() (*string, bool) {
	if o == nil || IsNil(o.TrackingCode) {
		return nil, false
	}
	return o.TrackingCode, true
}

// HasTrackingCode returns a boolean if a field has been set.
func (o *CreateReceiptShipmentRequest) HasTrackingCode() bool {
	if o != nil && !IsNil(o.TrackingCode) {
		return true
	}

	return false
}

// SetTrackingCode gets a reference to the given string and assigns it to the TrackingCode field.
func (o *CreateReceiptShipmentRequest) SetTrackingCode(v string) {
	o.TrackingCode = &v
}

// GetCarrierName returns the CarrierName field value if set, zero value otherwise.
func (o *CreateReceiptShipmentRequest) GetCarrierName() string {
	if o == nil || IsNil(o.CarrierName) {
		var ret string
		return ret
	}
	return *o.CarrierName
}

// GetCarrierNameOk returns a tuple with the CarrierName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReceiptShipmentRequest) GetCarrierNameOk() (*string, bool) {
	if o == nil || IsNil(o.CarrierName) {
		return nil, false
	}
	return o.CarrierName, true
}

// HasCarrierName returns a boolean if a field has been set.
func (o *CreateReceiptShipmentRequest) HasCarrierName() bool {
	if o != nil && !IsNil(o.CarrierName) {
		return true
	}

	return false
}

// SetCarrierName gets a reference to the given string and assigns it to the CarrierName field.
func (o *CreateReceiptShipmentRequest) SetCarrierName(v string) {
	o.CarrierName = &v
}

// GetSendBcc returns the SendBcc field value if set, zero value otherwise.
func (o *CreateReceiptShipmentRequest) GetSendBcc() bool {
	if o == nil || IsNil(o.SendBcc) {
		var ret bool
		return ret
	}
	return *o.SendBcc
}

// GetSendBccOk returns a tuple with the SendBcc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReceiptShipmentRequest) GetSendBccOk() (*bool, bool) {
	if o == nil || IsNil(o.SendBcc) {
		return nil, false
	}
	return o.SendBcc, true
}

// HasSendBcc returns a boolean if a field has been set.
func (o *CreateReceiptShipmentRequest) HasSendBcc() bool {
	if o != nil && !IsNil(o.SendBcc) {
		return true
	}

	return false
}

// SetSendBcc gets a reference to the given bool and assigns it to the SendBcc field.
func (o *CreateReceiptShipmentRequest) SetSendBcc(v bool) {
	o.SendBcc = &v
}

// GetNoteToBuyer returns the NoteToBuyer field value if set, zero value otherwise.
func (o *CreateReceiptShipmentRequest) GetNoteToBuyer() string {
	if o == nil || IsNil(o.NoteToBuyer) {
		var ret string
		return ret
	}
	return *o.NoteToBuyer
}

// GetNoteToBuyerOk returns a tuple with the NoteToBuyer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateReceiptShipmentRequest) GetNoteToBuyerOk() (*string, bool) {
	if o == nil || IsNil(o.NoteToBuyer) {
		return nil, false
	}
	return o.NoteToBuyer, true
}

// HasNoteToBuyer returns a boolean if a field has been set.
func (o *CreateReceiptShipmentRequest) HasNoteToBuyer() bool {
	if o != nil && !IsNil(o.NoteToBuyer) {
		return true
	}

	return false
}

// SetNoteToBuyer gets a reference to the given string and assigns it to the NoteToBuyer field.
func (o *CreateReceiptShipmentRequest) SetNoteToBuyer(v string) {
	o.NoteToBuyer = &v
}

func (o CreateReceiptShipmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateReceiptShipmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TrackingCode) {
		toSerialize["tracking_code"] = o.TrackingCode
	}
	if !IsNil(o.CarrierName) {
		toSerialize["carrier_name"] = o.CarrierName
	}
	if !IsNil(o.SendBcc) {
		toSerialize["send_bcc"] = o.SendBcc
	}
	if !IsNil(o.NoteToBuyer) {
		toSerialize["note_to_buyer"] = o.NoteToBuyer
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableCreateReceiptShipmentRequest struct {
	value *CreateReceiptShipmentRequest
	isSet bool
}

func (v NullableCreateReceiptShipmentRequest) Get() *CreateReceiptShipmentRequest {
	return v.value
}

func (v *NullableCreateReceiptShipmentRequest) Set(val *CreateReceiptShipmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateReceiptShipmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateReceiptShipmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateReceiptShipmentRequest(val *CreateReceiptShipmentRequest) *NullableCreateReceiptShipmentRequest {
	return &NullableCreateReceiptShipmentRequest{value: val, isSet: true}
}

func (v NullableCreateReceiptShipmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateReceiptShipmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
