/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2026 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
	"fmt"
	"strings"
	"unicode"
)

// UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType The type of the personalization question. Note: Currently, only a single question with type 'text_input' is supported. See https://developers.etsy.com/documentation/tutorials/personalization-migration for details about new question types.
type UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType string

// List of updateListingPersonalization_request_personalization_questions_inner_question_type
const (
	UPDATELISTINGPERSONALIZATIONREQUESTPERSONALIZATIONQUESTIONSINNERQUESTIONTYPE_TEXT_INPUT UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType = "text_input"
)

// All allowed values of UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType enum
var AllowedUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionTypeEnumValues = []UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType{
	"text_input",
}

var AllowedUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionTypeEnumValuesValidator = map[interface{}]struct{}{
	UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType("text_input").Ptr().generateNormalizedEnum(): struct{}{},
}

func (v *UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType) generateNormalizedEnum() any {
	if v == nil {
		return nil
	}

	s := *v
	var sb strings.Builder
	sb.Grow(len(s) + 2)     // Preallocate memory for efficiency
	var prevUnderscore bool // Track consecutive underscores
	for i, r := range s {
		switch {
		case unicode.IsUpper(r):
			// Add an underscore if:
			// 1. Not the first character
			// 2. Previous character is NOT uppercase (to handle acronyms like "HTTPRequest")
			// 3. Next character is lowercase (to avoid splitting acronyms)
			if i > 0 && (!unicode.IsUpper(rune(s[i-1])) || (i+1 < len(s) && unicode.IsLower(rune(s[i+1])))) {
				sb.WriteByte('_')
			}
			sb.WriteRune(unicode.ToLower(r))
			prevUnderscore = false

		case unicode.IsSpace(r) || r == '-' || r == '_': // Convert spaces, dashes, and underscores to `_`
			if !prevUnderscore { // Avoid consecutive `_`
				sb.WriteByte('_')
				prevUnderscore = true
			}

		case unicode.IsLetter(r) || unicode.IsDigit(r): // Keep letters and numbers
			sb.WriteRune(r)
			prevUnderscore = false

		default:
			// Ignore symbols (e.g., `@#$%&*!`)
		}
	}

	// Trim leading/trailing underscores
	return strings.Trim(sb.String(), "_")

}

func (v *UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType(value)
	if _, existing := AllowedUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionTypeEnumValuesValidator[enumTypeValue.Ptr().generateNormalizedEnum()]; existing {
		*v = enumTypeValue
		return nil
	}

	return fmt.Errorf("%+v is not a valid UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType", value)
}

// NewUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionTypeFromValue returns a pointer to a valid UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionTypeFromValue(v string) (*UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType, error) {
	ev := UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType: valid values are %v", v, AllowedUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType) IsValid() bool {
	for _, existing := range AllowedUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to updateListingPersonalization_request_personalization_questions_inner_question_type value
func (v UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType) Ptr() *UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType {
	return &v
}

type NullableUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType struct {
	value *UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType
	isSet bool
}

func (v NullableUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType) Get() *UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType {
	return v.value
}

func (v *NullableUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType) Set(val *UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType(val *UpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType) *NullableUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType {
	return &NullableUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType{value: val, isSet: true}
}

func (v NullableUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateListingPersonalizationRequestPersonalizationQuestionsInnerQuestionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
