/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2026 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
)

// checks if the UpdateListingPersonalizationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateListingPersonalizationRequest{}

// UpdateListingPersonalizationRequest struct for UpdateListingPersonalizationRequest
type UpdateListingPersonalizationRequest struct {
	PersonalizationQuestions []UpdateListingPersonalizationRequestPersonalizationQuestionsInner `json:"personalization_questions"`
	AdditionalProperties     map[string]interface{}
}

type _UpdateListingPersonalizationRequest UpdateListingPersonalizationRequest

// NewUpdateListingPersonalizationRequest instantiates a new UpdateListingPersonalizationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateListingPersonalizationRequest(personalizationQuestions []UpdateListingPersonalizationRequestPersonalizationQuestionsInner) *UpdateListingPersonalizationRequest {
	this := UpdateListingPersonalizationRequest{}
	this.PersonalizationQuestions = personalizationQuestions
	return &this
}

// NewUpdateListingPersonalizationRequestWithDefaults instantiates a new UpdateListingPersonalizationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateListingPersonalizationRequestWithDefaults() *UpdateListingPersonalizationRequest {
	this := UpdateListingPersonalizationRequest{}
	return &this
}

// GetPersonalizationQuestions returns the PersonalizationQuestions field value
func (o *UpdateListingPersonalizationRequest) GetPersonalizationQuestions() []UpdateListingPersonalizationRequestPersonalizationQuestionsInner {
	if o == nil {
		var ret []UpdateListingPersonalizationRequestPersonalizationQuestionsInner
		return ret
	}

	return o.PersonalizationQuestions
}

// GetPersonalizationQuestionsOk returns a tuple with the PersonalizationQuestions field value
// and a boolean to check if the value has been set.
func (o *UpdateListingPersonalizationRequest) GetPersonalizationQuestionsOk() ([]UpdateListingPersonalizationRequestPersonalizationQuestionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.PersonalizationQuestions, true
}

// SetPersonalizationQuestions sets field value
func (o *UpdateListingPersonalizationRequest) SetPersonalizationQuestions(v []UpdateListingPersonalizationRequestPersonalizationQuestionsInner) {
	o.PersonalizationQuestions = v
}

func (o UpdateListingPersonalizationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateListingPersonalizationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["personalization_questions"] = o.PersonalizationQuestions

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateListingPersonalizationRequest struct {
	value *UpdateListingPersonalizationRequest
	isSet bool
}

func (v NullableUpdateListingPersonalizationRequest) Get() *UpdateListingPersonalizationRequest {
	return v.value
}

func (v *NullableUpdateListingPersonalizationRequest) Set(val *UpdateListingPersonalizationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateListingPersonalizationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateListingPersonalizationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateListingPersonalizationRequest(val *UpdateListingPersonalizationRequest) *NullableUpdateListingPersonalizationRequest {
	return &NullableUpdateListingPersonalizationRequest{value: val, isSet: true}
}

func (v NullableUpdateListingPersonalizationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateListingPersonalizationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
