/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2024 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"unicode"
)

// CreateDraftListingRequestWhoMade An enumerated string indicating who made the product. Helps buyers locate the listing under the Handmade heading. Requires 'is_supply' and 'when_made'.
type CreateDraftListingRequestWhoMade string

// List of createDraftListing_request_who_made
const (
	CREATEDRAFTLISTINGREQUESTWHOMADE_I_DID        CreateDraftListingRequestWhoMade = "i_did"
	CREATEDRAFTLISTINGREQUESTWHOMADE_SOMEONE_ELSE CreateDraftListingRequestWhoMade = "someone_else"
	CREATEDRAFTLISTINGREQUESTWHOMADE_COLLECTIVE   CreateDraftListingRequestWhoMade = "collective"
)

// All allowed values of CreateDraftListingRequestWhoMade enum
var AllowedCreateDraftListingRequestWhoMadeEnumValues = []CreateDraftListingRequestWhoMade{
	"i_did",
	"someone_else",
	"collective",
}

var AllowedCreateDraftListingRequestWhoMadeEnumValuesValidator = map[interface{}]struct{}{
	CreateDraftListingRequestWhoMade("i_did").Ptr().generateNormalizedEnum():        struct{}{},
	CreateDraftListingRequestWhoMade("someone_else").Ptr().generateNormalizedEnum(): struct{}{},
	CreateDraftListingRequestWhoMade("collective").Ptr().generateNormalizedEnum():   struct{}{},
}

func (v *CreateDraftListingRequestWhoMade) generateNormalizedEnum() any {
	if v == nil {
		return nil
	}

	s := *v
	if reflect.TypeOf(*v).Kind() != reflect.String {
		return s
	}

	var sb strings.Builder
	sb.Grow(len(s) + 2)     // Preallocate memory for efficiency
	var prevUnderscore bool // Track consecutive underscores
	for i, r := range s {
		switch {
		case unicode.IsUpper(r):
			// Add an underscore if:
			// 1. Not the first character
			// 2. Previous character is NOT uppercase (to handle acronyms like "HTTPRequest")
			// 3. Next character is lowercase (to avoid splitting acronyms)
			if i > 0 && (!unicode.IsUpper(rune(s[i-1])) || (i+1 < len(s) && unicode.IsLower(rune(s[i+1])))) {
				sb.WriteByte('_')
			}
			sb.WriteRune(unicode.ToLower(r))
			prevUnderscore = false

		case unicode.IsSpace(r) || r == '-' || r == '_': // Convert spaces, dashes, and underscores to `_`
			if !prevUnderscore { // Avoid consecutive `_`
				sb.WriteByte('_')
				prevUnderscore = true
			}

		case unicode.IsLetter(r) || unicode.IsDigit(r): // Keep letters and numbers
			sb.WriteRune(r)
			prevUnderscore = false

		default:
			// Ignore symbols (e.g., `@#$%&*!`)
		}
	}

	// Trim leading/trailing underscores
	return strings.Trim(sb.String(), "_")
}

func (v *CreateDraftListingRequestWhoMade) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CreateDraftListingRequestWhoMade(value)
	if _, existing := AllowedCreateDraftListingRequestWhoMadeEnumValuesValidator[enumTypeValue.Ptr().generateNormalizedEnum()]; existing {
		*v = enumTypeValue
		return nil
	}

	return fmt.Errorf("%+v is not a valid CreateDraftListingRequestWhoMade", value)
}

// NewCreateDraftListingRequestWhoMadeFromValue returns a pointer to a valid CreateDraftListingRequestWhoMade
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCreateDraftListingRequestWhoMadeFromValue(v string) (*CreateDraftListingRequestWhoMade, error) {
	ev := CreateDraftListingRequestWhoMade(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CreateDraftListingRequestWhoMade: valid values are %v", v, AllowedCreateDraftListingRequestWhoMadeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CreateDraftListingRequestWhoMade) IsValid() bool {
	for _, existing := range AllowedCreateDraftListingRequestWhoMadeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to createDraftListing_request_who_made value
func (v CreateDraftListingRequestWhoMade) Ptr() *CreateDraftListingRequestWhoMade {
	return &v
}

type NullableCreateDraftListingRequestWhoMade struct {
	value *CreateDraftListingRequestWhoMade
	isSet bool
}

func (v NullableCreateDraftListingRequestWhoMade) Get() *CreateDraftListingRequestWhoMade {
	return v.value
}

func (v *NullableCreateDraftListingRequestWhoMade) Set(val *CreateDraftListingRequestWhoMade) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDraftListingRequestWhoMade) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDraftListingRequestWhoMade) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDraftListingRequestWhoMade(val *CreateDraftListingRequestWhoMade) *NullableCreateDraftListingRequestWhoMade {
	return &NullableCreateDraftListingRequestWhoMade{value: val, isSet: true}
}

func (v NullableCreateDraftListingRequestWhoMade) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDraftListingRequestWhoMade) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
