/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2024 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
	"fmt"
)

// ShopListingWhoMade An enumerated string indicating who made the product. Helps buyers locate the listing under the Handmade heading. Requires 'is_supply' and 'when_made'.
type ShopListingWhoMade string

// List of ShopListing_who_made
const (
	SHOPLISTINGWHOMADE_I_DID        ShopListingWhoMade = "i_did"
	SHOPLISTINGWHOMADE_SOMEONE_ELSE ShopListingWhoMade = "someone_else"
	SHOPLISTINGWHOMADE_COLLECTIVE   ShopListingWhoMade = "collective"
)

// All allowed values of ShopListingWhoMade enum
var AllowedShopListingWhoMadeEnumValues = []ShopListingWhoMade{
	"i_did",
	"someone_else",
	"collective",
}

func (v *ShopListingWhoMade) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ShopListingWhoMade(value)
	for _, existing := range AllowedShopListingWhoMadeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ShopListingWhoMade", value)
}

// NewShopListingWhoMadeFromValue returns a pointer to a valid ShopListingWhoMade
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewShopListingWhoMadeFromValue(v string) (*ShopListingWhoMade, error) {
	ev := ShopListingWhoMade(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ShopListingWhoMade: valid values are %v", v, AllowedShopListingWhoMadeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ShopListingWhoMade) IsValid() bool {
	for _, existing := range AllowedShopListingWhoMadeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ShopListing_who_made value
func (v ShopListingWhoMade) Ptr() *ShopListingWhoMade {
	return &v
}

type NullableShopListingWhoMade struct {
	value *ShopListingWhoMade
	isSet bool
}

func (v NullableShopListingWhoMade) Get() *ShopListingWhoMade {
	return v.value
}

func (v *NullableShopListingWhoMade) Set(val *ShopListingWhoMade) {
	v.value = val
	v.isSet = true
}

func (v NullableShopListingWhoMade) IsSet() bool {
	return v.isSet
}

func (v *NullableShopListingWhoMade) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShopListingWhoMade(val *ShopListingWhoMade) *NullableShopListingWhoMade {
	return &NullableShopListingWhoMade{value: val, isSet: true}
}

func (v NullableShopListingWhoMade) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShopListingWhoMade) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
