/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2026 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
)

// checks if the UpdateShopShippingProfileUpgradeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateShopShippingProfileUpgradeRequest{}

// UpdateShopShippingProfileUpgradeRequest struct for UpdateShopShippingProfileUpgradeRequest
type UpdateShopShippingProfileUpgradeRequest struct {
	// Name for the shipping upgrade shown to shoppers at checkout, e.g. USPS Priority.
	UpgradeName *string                                      `json:"upgrade_name,omitempty"`
	Type        *CreateShopShippingProfileUpgradeRequestType `json:"type,omitempty"`
	// Additional cost of adding the shipping upgrade.
	Price *float32 `json:"price,omitempty"`
	// Additional cost of adding the shipping upgrade for each additional item.
	SecondaryPrice *float32 `json:"secondary_price,omitempty"`
	// The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with `mail_class`** if `min_delivery_days` and `max_delivery_days` are null.
	ShippingCarrierId *int64 `json:"shipping_carrier_id,omitempty"`
	// The unique ID string of a shipping carrier's mail class, which is used to calculate an estimated delivery date. **Required with `shipping_carrier_id`** if `min_delivery_days` and `max_delivery_days` are null.
	MailClass *string `json:"mail_class,omitempty"`
	// The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `max_delivery_days`** if `mail_class` is null.
	MinDeliveryDays *int64 `json:"min_delivery_days,omitempty"`
	// The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `min_delivery_days`** if `mail_class` is null.
	MaxDeliveryDays      *int64 `json:"max_delivery_days,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateShopShippingProfileUpgradeRequest UpdateShopShippingProfileUpgradeRequest

// NewUpdateShopShippingProfileUpgradeRequest instantiates a new UpdateShopShippingProfileUpgradeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateShopShippingProfileUpgradeRequest() *UpdateShopShippingProfileUpgradeRequest {
	this := UpdateShopShippingProfileUpgradeRequest{}
	return &this
}

// NewUpdateShopShippingProfileUpgradeRequestWithDefaults instantiates a new UpdateShopShippingProfileUpgradeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateShopShippingProfileUpgradeRequestWithDefaults() *UpdateShopShippingProfileUpgradeRequest {
	this := UpdateShopShippingProfileUpgradeRequest{}
	return &this
}

// GetUpgradeName returns the UpgradeName field value if set, zero value otherwise.
func (o *UpdateShopShippingProfileUpgradeRequest) GetUpgradeName() string {
	if o == nil || IsNil(o.UpgradeName) {
		var ret string
		return ret
	}
	return *o.UpgradeName
}

// GetUpgradeNameOk returns a tuple with the UpgradeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) GetUpgradeNameOk() (*string, bool) {
	if o == nil || IsNil(o.UpgradeName) {
		return nil, false
	}
	return o.UpgradeName, true
}

// HasUpgradeName returns a boolean if a field has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) HasUpgradeName() bool {
	if o != nil && !IsNil(o.UpgradeName) {
		return true
	}

	return false
}

// SetUpgradeName gets a reference to the given string and assigns it to the UpgradeName field.
func (o *UpdateShopShippingProfileUpgradeRequest) SetUpgradeName(v string) {
	o.UpgradeName = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *UpdateShopShippingProfileUpgradeRequest) GetType() CreateShopShippingProfileUpgradeRequestType {
	if o == nil || IsNil(o.Type) {
		var ret CreateShopShippingProfileUpgradeRequestType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) GetTypeOk() (*CreateShopShippingProfileUpgradeRequestType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given CreateShopShippingProfileUpgradeRequestType and assigns it to the Type field.
func (o *UpdateShopShippingProfileUpgradeRequest) SetType(v CreateShopShippingProfileUpgradeRequestType) {
	o.Type = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *UpdateShopShippingProfileUpgradeRequest) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *UpdateShopShippingProfileUpgradeRequest) SetPrice(v float32) {
	o.Price = &v
}

// GetSecondaryPrice returns the SecondaryPrice field value if set, zero value otherwise.
func (o *UpdateShopShippingProfileUpgradeRequest) GetSecondaryPrice() float32 {
	if o == nil || IsNil(o.SecondaryPrice) {
		var ret float32
		return ret
	}
	return *o.SecondaryPrice
}

// GetSecondaryPriceOk returns a tuple with the SecondaryPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) GetSecondaryPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.SecondaryPrice) {
		return nil, false
	}
	return o.SecondaryPrice, true
}

// HasSecondaryPrice returns a boolean if a field has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) HasSecondaryPrice() bool {
	if o != nil && !IsNil(o.SecondaryPrice) {
		return true
	}

	return false
}

// SetSecondaryPrice gets a reference to the given float32 and assigns it to the SecondaryPrice field.
func (o *UpdateShopShippingProfileUpgradeRequest) SetSecondaryPrice(v float32) {
	o.SecondaryPrice = &v
}

// GetShippingCarrierId returns the ShippingCarrierId field value if set, zero value otherwise.
func (o *UpdateShopShippingProfileUpgradeRequest) GetShippingCarrierId() int64 {
	if o == nil || IsNil(o.ShippingCarrierId) {
		var ret int64
		return ret
	}
	return *o.ShippingCarrierId
}

// GetShippingCarrierIdOk returns a tuple with the ShippingCarrierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) GetShippingCarrierIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ShippingCarrierId) {
		return nil, false
	}
	return o.ShippingCarrierId, true
}

// HasShippingCarrierId returns a boolean if a field has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) HasShippingCarrierId() bool {
	if o != nil && !IsNil(o.ShippingCarrierId) {
		return true
	}

	return false
}

// SetShippingCarrierId gets a reference to the given int64 and assigns it to the ShippingCarrierId field.
func (o *UpdateShopShippingProfileUpgradeRequest) SetShippingCarrierId(v int64) {
	o.ShippingCarrierId = &v
}

// GetMailClass returns the MailClass field value if set, zero value otherwise.
func (o *UpdateShopShippingProfileUpgradeRequest) GetMailClass() string {
	if o == nil || IsNil(o.MailClass) {
		var ret string
		return ret
	}
	return *o.MailClass
}

// GetMailClassOk returns a tuple with the MailClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) GetMailClassOk() (*string, bool) {
	if o == nil || IsNil(o.MailClass) {
		return nil, false
	}
	return o.MailClass, true
}

// HasMailClass returns a boolean if a field has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) HasMailClass() bool {
	if o != nil && !IsNil(o.MailClass) {
		return true
	}

	return false
}

// SetMailClass gets a reference to the given string and assigns it to the MailClass field.
func (o *UpdateShopShippingProfileUpgradeRequest) SetMailClass(v string) {
	o.MailClass = &v
}

// GetMinDeliveryDays returns the MinDeliveryDays field value if set, zero value otherwise.
func (o *UpdateShopShippingProfileUpgradeRequest) GetMinDeliveryDays() int64 {
	if o == nil || IsNil(o.MinDeliveryDays) {
		var ret int64
		return ret
	}
	return *o.MinDeliveryDays
}

// GetMinDeliveryDaysOk returns a tuple with the MinDeliveryDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) GetMinDeliveryDaysOk() (*int64, bool) {
	if o == nil || IsNil(o.MinDeliveryDays) {
		return nil, false
	}
	return o.MinDeliveryDays, true
}

// HasMinDeliveryDays returns a boolean if a field has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) HasMinDeliveryDays() bool {
	if o != nil && !IsNil(o.MinDeliveryDays) {
		return true
	}

	return false
}

// SetMinDeliveryDays gets a reference to the given int64 and assigns it to the MinDeliveryDays field.
func (o *UpdateShopShippingProfileUpgradeRequest) SetMinDeliveryDays(v int64) {
	o.MinDeliveryDays = &v
}

// GetMaxDeliveryDays returns the MaxDeliveryDays field value if set, zero value otherwise.
func (o *UpdateShopShippingProfileUpgradeRequest) GetMaxDeliveryDays() int64 {
	if o == nil || IsNil(o.MaxDeliveryDays) {
		var ret int64
		return ret
	}
	return *o.MaxDeliveryDays
}

// GetMaxDeliveryDaysOk returns a tuple with the MaxDeliveryDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) GetMaxDeliveryDaysOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxDeliveryDays) {
		return nil, false
	}
	return o.MaxDeliveryDays, true
}

// HasMaxDeliveryDays returns a boolean if a field has been set.
func (o *UpdateShopShippingProfileUpgradeRequest) HasMaxDeliveryDays() bool {
	if o != nil && !IsNil(o.MaxDeliveryDays) {
		return true
	}

	return false
}

// SetMaxDeliveryDays gets a reference to the given int64 and assigns it to the MaxDeliveryDays field.
func (o *UpdateShopShippingProfileUpgradeRequest) SetMaxDeliveryDays(v int64) {
	o.MaxDeliveryDays = &v
}

func (o UpdateShopShippingProfileUpgradeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateShopShippingProfileUpgradeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UpgradeName) {
		toSerialize["upgrade_name"] = o.UpgradeName
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.SecondaryPrice) {
		toSerialize["secondary_price"] = o.SecondaryPrice
	}
	if !IsNil(o.ShippingCarrierId) {
		toSerialize["shipping_carrier_id"] = o.ShippingCarrierId
	}
	if !IsNil(o.MailClass) {
		toSerialize["mail_class"] = o.MailClass
	}
	if !IsNil(o.MinDeliveryDays) {
		toSerialize["min_delivery_days"] = o.MinDeliveryDays
	}
	if !IsNil(o.MaxDeliveryDays) {
		toSerialize["max_delivery_days"] = o.MaxDeliveryDays
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateShopShippingProfileUpgradeRequest struct {
	value *UpdateShopShippingProfileUpgradeRequest
	isSet bool
}

func (v NullableUpdateShopShippingProfileUpgradeRequest) Get() *UpdateShopShippingProfileUpgradeRequest {
	return v.value
}

func (v *NullableUpdateShopShippingProfileUpgradeRequest) Set(val *UpdateShopShippingProfileUpgradeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateShopShippingProfileUpgradeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateShopShippingProfileUpgradeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateShopShippingProfileUpgradeRequest(val *UpdateShopShippingProfileUpgradeRequest) *NullableUpdateShopShippingProfileUpgradeRequest {
	return &NullableUpdateShopShippingProfileUpgradeRequest{value: val, isSet: true}
}

func (v NullableUpdateShopShippingProfileUpgradeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateShopShippingProfileUpgradeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
