/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2026 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goEtsy

import (
	"encoding/json"
)

// checks if the UpdateShopReceiptRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateShopReceiptRequest{}

// UpdateShopReceiptRequest struct for UpdateShopReceiptRequest
type UpdateShopReceiptRequest struct {
	// When `true`, returns receipts where the seller shipped the product(s) in this receipt. When `false`, returns receipts where shipment has not been set.
	WasShipped NullableBool `json:"was_shipped,omitempty"`
	// When `true`, returns receipts where the seller has recieved payment for the receipt. When `false`, returns receipts where payment has not been received.
	WasPaid              NullableBool `json:"was_paid,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateShopReceiptRequest UpdateShopReceiptRequest

// NewUpdateShopReceiptRequest instantiates a new UpdateShopReceiptRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateShopReceiptRequest() *UpdateShopReceiptRequest {
	this := UpdateShopReceiptRequest{}
	return &this
}

// NewUpdateShopReceiptRequestWithDefaults instantiates a new UpdateShopReceiptRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateShopReceiptRequestWithDefaults() *UpdateShopReceiptRequest {
	this := UpdateShopReceiptRequest{}
	return &this
}

// GetWasShipped returns the WasShipped field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateShopReceiptRequest) GetWasShipped() bool {
	if o == nil || IsNil(o.WasShipped.Get()) {
		var ret bool
		return ret
	}
	return *o.WasShipped.Get()
}

// GetWasShippedOk returns a tuple with the WasShipped field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateShopReceiptRequest) GetWasShippedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.WasShipped.Get(), o.WasShipped.IsSet()
}

// HasWasShipped returns a boolean if a field has been set.
func (o *UpdateShopReceiptRequest) HasWasShipped() bool {
	if o != nil && o.WasShipped.IsSet() {
		return true
	}

	return false
}

// SetWasShipped gets a reference to the given NullableBool and assigns it to the WasShipped field.
func (o *UpdateShopReceiptRequest) SetWasShipped(v bool) {
	o.WasShipped.Set(&v)
}

// SetWasShippedNil sets the value for WasShipped to be an explicit nil
func (o *UpdateShopReceiptRequest) SetWasShippedNil() {
	o.WasShipped.Set(nil)
}

// UnsetWasShipped ensures that no value is present for WasShipped, not even an explicit nil
func (o *UpdateShopReceiptRequest) UnsetWasShipped() {
	o.WasShipped.Unset()
}

// GetWasPaid returns the WasPaid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateShopReceiptRequest) GetWasPaid() bool {
	if o == nil || IsNil(o.WasPaid.Get()) {
		var ret bool
		return ret
	}
	return *o.WasPaid.Get()
}

// GetWasPaidOk returns a tuple with the WasPaid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateShopReceiptRequest) GetWasPaidOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.WasPaid.Get(), o.WasPaid.IsSet()
}

// HasWasPaid returns a boolean if a field has been set.
func (o *UpdateShopReceiptRequest) HasWasPaid() bool {
	if o != nil && o.WasPaid.IsSet() {
		return true
	}

	return false
}

// SetWasPaid gets a reference to the given NullableBool and assigns it to the WasPaid field.
func (o *UpdateShopReceiptRequest) SetWasPaid(v bool) {
	o.WasPaid.Set(&v)
}

// SetWasPaidNil sets the value for WasPaid to be an explicit nil
func (o *UpdateShopReceiptRequest) SetWasPaidNil() {
	o.WasPaid.Set(nil)
}

// UnsetWasPaid ensures that no value is present for WasPaid, not even an explicit nil
func (o *UpdateShopReceiptRequest) UnsetWasPaid() {
	o.WasPaid.Unset()
}

func (o UpdateShopReceiptRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateShopReceiptRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.WasShipped.IsSet() {
		toSerialize["was_shipped"] = o.WasShipped.Get()
	}
	if o.WasPaid.IsSet() {
		toSerialize["was_paid"] = o.WasPaid.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateShopReceiptRequest struct {
	value *UpdateShopReceiptRequest
	isSet bool
}

func (v NullableUpdateShopReceiptRequest) Get() *UpdateShopReceiptRequest {
	return v.value
}

func (v *NullableUpdateShopReceiptRequest) Set(val *UpdateShopReceiptRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateShopReceiptRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateShopReceiptRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateShopReceiptRequest(val *UpdateShopReceiptRequest) *NullableUpdateShopReceiptRequest {
	return &NullableUpdateShopReceiptRequest{value: val, isSet: true}
}

func (v NullableUpdateShopReceiptRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateShopReceiptRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
