/*
Etsy Open API v3

Testing ShopListingInventoryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package goEtsy

import (
	"context"
	"testing"

	openapiclient "github.com/gearment/go-etsy/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_goEtsy_ShopListingInventoryAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ShopListingInventoryAPIService GetListingInventory", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var listingId int64

		resp, httpRes, err := apiClient.ShopListingInventoryAPI.GetListingInventory(context.Background(), listingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShopListingInventoryAPIService UpdateListingInventory", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var listingId int64

		resp, httpRes, err := apiClient.ShopListingInventoryAPI.UpdateListingInventory(context.Background(), listingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
