/*
Etsy Open API v3

Testing ShopHolidayPreferencesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package goEtsy

import (
	"context"
	"testing"

	openapiclient "github.com/gearment/go-etsy/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_goEtsy_ShopHolidayPreferencesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ShopHolidayPreferencesAPIService GetHolidayPreferences", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var shopId int64

		resp, httpRes, err := apiClient.ShopHolidayPreferencesAPI.GetHolidayPreferences(context.Background(), shopId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShopHolidayPreferencesAPIService UpdateHolidayPreferences", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var shopId int64
		var holidayId UpdateHolidayPreferencesHolidayIdParameter

		resp, httpRes, err := apiClient.ShopHolidayPreferencesAPI.UpdateHolidayPreferences(context.Background(), shopId, holidayId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
