/*
Etsy Open API v3

Testing ShopListingVideoAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package goEtsy

import (
	"context"
	"testing"

	openapiclient "github.com/gearment/go-etsy/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_goEtsy_ShopListingVideoAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ShopListingVideoAPIService DeleteListingVideo", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var shopId int64
		var listingId int64
		var videoId int64

		httpRes, err := apiClient.ShopListingVideoAPI.DeleteListingVideo(context.Background(), shopId, listingId, videoId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShopListingVideoAPIService GetListingVideo", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var videoId int64
		var listingId int64

		resp, httpRes, err := apiClient.ShopListingVideoAPI.GetListingVideo(context.Background(), videoId, listingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShopListingVideoAPIService GetListingVideos", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var listingId int64

		resp, httpRes, err := apiClient.ShopListingVideoAPI.GetListingVideos(context.Background(), listingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShopListingVideoAPIService UploadListingVideo", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var shopId int64
		var listingId int64

		resp, httpRes, err := apiClient.ShopListingVideoAPI.UploadListingVideo(context.Background(), shopId, listingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
