/*
Etsy Open API v3

Testing ShopListingFileAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package goEtsy

import (
	"context"
	"testing"

	openapiclient "github.com/gearment/go-etsy/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_goEtsy_ShopListingFileAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ShopListingFileAPIService DeleteListingFile", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var shopId int64
		var listingId int64
		var listingFileId int64

		httpRes, err := apiClient.ShopListingFileAPI.DeleteListingFile(context.Background(), shopId, listingId, listingFileId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShopListingFileAPIService GetAllListingFiles", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var listingId int64
		var shopId int64

		resp, httpRes, err := apiClient.ShopListingFileAPI.GetAllListingFiles(context.Background(), listingId, shopId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShopListingFileAPIService GetListingFile", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var shopId int64
		var listingId int64
		var listingFileId int64

		resp, httpRes, err := apiClient.ShopListingFileAPI.GetListingFile(context.Background(), shopId, listingId, listingFileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShopListingFileAPIService UploadListingFile", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var shopId int64
		var listingId int64

		resp, httpRes, err := apiClient.ShopListingFileAPI.UploadListingFile(context.Background(), shopId, listingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
