/*
Etsy Open API v3

Testing ShopListingVariationImageAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package goEtsy

import (
	"context"
	"testing"

	openapiclient "github.com/gearment/go-etsy/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_goEtsy_ShopListingVariationImageAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ShopListingVariationImageAPIService GetListingVariationImages", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var shopId int64
		var listingId int64

		resp, httpRes, err := apiClient.ShopListingVariationImageAPI.GetListingVariationImages(context.Background(), shopId, listingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShopListingVariationImageAPIService UpdateVariationImages", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var shopId int64
		var listingId int64

		resp, httpRes, err := apiClient.ShopListingVariationImageAPI.UpdateVariationImages(context.Background(), shopId, listingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
